// ============================================================
// Greek Vocabulary Database
// ------------------------------------------------------------
// Each set has: id, source, chapter, title, and words. The chapter is
// the workbook chapter the page came from; it drives the chapter picker,
// and can be reassigned in Settings without editing this file.
// Each word: g (Greek lexical form), gloss (English), freq (NT
// frequency count from the workbook), tier ('memorize' | 'recognize'),
// icon (a symbol shown with the hint) and mn (the built-in memory hook).
//
// To add new vocabulary: upload workbook photos to Claude and a
// new set object gets appended here. Custom sets added in-app are
// stored in localStorage and merged at runtime.
// ============================================================

const VOCAB_SETS = [
  {
    id: "gd-set-01",
    source: "Going Deeper with New Testament Greek",
    chapter: 2,
    title: "Chapter 2 — Mark 1 Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀπαγγέλλω", gloss: "I announce, proclaim, report", freq: 45, tier: "memorize", icon: "📢", mn: "ah-pahng-GHEHL-lo ≈ \"a PANG — hard-G HELLO!\" A pang, then you hail everyone: ANNOUNCE." },
      { g: "ἀποδίδωμι", gloss: "I give away, pay, return", freq: 48, tier: "memorize", icon: "💰", mn: "ah-po-THEE-tho-mee ≈ \"a-PO-THEE-tho-me.\" ἀπό back + δίδωμι give — hand it back over: I PAY, I RETURN." },
      { g: "ἄρα", gloss: "so, then, consequently", freq: 49, tier: "memorize", icon: "➡️", mn: "AH-rah ≈ \"AH — RAH!\" The cheer once the point lands: SO, THEN." },
      { g: "ἄφεσις, -εως, ἡ", gloss: "forgiveness", freq: 17, tier: "memorize", icon: "🕊️", mn: "ah-FEH-sees ≈ \"a-FESS-sis.\" Fess up, sis — and it is FORGIVEN." },
      { g: "ἄχρι", gloss: "until (conj. or prep. + gen.)", freq: 49, tier: "memorize", icon: "⏳", mn: "AH-khree ≈ \"a CRY\" (rasped: kh). You cry UNTIL it is over." },
      { g: "βάπτισμα, -ατος, τό", gloss: "baptism", freq: 19, tier: "memorize", icon: "💧", mn: "VAHP-tees-mah ≈ \"VOP-TEASE-ma.\" Spelled βαπτ-, our BAPTISM — Koine β says \"v\"." },
      { g: "δεύτερος", gloss: "second", freq: 43, tier: "memorize", icon: "2️⃣", mn: "THEV-teh-ros ≈ \"THE-VET-ROSE.\" Spelled δευτ-, our DEUTERONOMY: the SECOND law." },
      { g: "διακονέω", gloss: "I serve", freq: 37, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEH-o ≈ \"THEE-a-ko-NAY-o.\" Spelled διακον-, our DEACON, who waits the tables: I SERVE." },
      { g: "διέρχομαι", gloss: "I go through, cross over", freq: 43, tier: "memorize", icon: "🚶", mn: "thee-EHR-kho-meh ≈ \"THE-AIR-I-COMB.\" You comb right THROUGH the air." },
      { g: "ἐκπορεύομαι", gloss: "I go out, come out", freq: 33, tier: "memorize", icon: "🚪", mn: "ehk-po-REV-o-meh ≈ \"ECK-po-REV-o-me.\" Rev it up and GO OUT." },
      { g: "ἐνδύω", gloss: "I clothe myself, put on, wear", freq: 27, tier: "memorize", icon: "👕", mn: "ehn-THEW-o ≈ \"en-THEW-oh.\" A DUO of sleeves goes on at once — our own en-DUE: I PUT ON, I WEAR." },
      { g: "ἐπιγινώσκω", gloss: "I know, understand, recognize", freq: 44, tier: "memorize", icon: "💡", mn: "eh-pee-ghee-NOS-ko ≈ \"a-PIGGY-KNOWS-ko.\" A piggy KNOWS you: RECOGNIZE." },
      { g: "ἔρημος, ἡ", gloss: "desert, wilderness", freq: 48, tier: "memorize", icon: "🏜️", mn: "EH-ray-mos ≈ \"AIR-RAY-MOSS.\" Air and rays, no moss at all: the DESERT." },
      { g: "ἑτοιμάζω", gloss: "I make ready, prepare", freq: 40, tier: "memorize", icon: "🧰", mn: "heh-TEW-mah-zo ≈ \"he-and-YOU-ma-zo.\" He and YOU get it all READY together." },
      { g: "ἔτος, -ους, τό", gloss: "year", freq: 49, tier: "memorize", icon: "📅", mn: "EH-tos ≈ \"a TOSS.\" You toss the old calendar out each YEAR." },
      { g: "εὐδοκέω", gloss: "I am well pleased, approve", freq: 21, tier: "memorize", icon: "😊", mn: "ev-tho-KEH-o ≈ \"EV-tho-KAY-o.\" εὖ well + δοκέω seem: it seems good to him — WELL PLEASED." },
      { g: "Ἠσαΐας, ὁ", gloss: "Isaiah", freq: 22, tier: "memorize", icon: "📜", mn: "ay-sah-EE-ahs ≈ \"a-SAY-EE-as.\" Say it and you have ISAIAH." },
      { g: "θηρίον, τό", gloss: "animal, beast", freq: 46, tier: "memorize", icon: "🦁", mn: "THAY-ree-on ≈ \"THEY'RE-ON.\" They're on me — the wild BEASTS!" },
      { g: "θλῖψις, -εως, ἡ", gloss: "tribulation, affliction, oppression", freq: 45, tier: "memorize", icon: "😰", mn: "THLEEP-sees ≈ \"the-LIPS-SEIZE.\" The lips seize under the pressure: TRIBULATION." },
      { g: "θρίξ, τριχός, ἡ", gloss: "hair", freq: 15, tier: "memorize", icon: "💇", mn: "THREEX ≈ \"THREE-X.\" Three strands of HAIR crossed in an X." },
      { g: "ἱκανός", gloss: "qualified, able", freq: 39, tier: "memorize", icon: "✅", mn: "hee-kah-NOS ≈ \"HE-CAN-nose.\" He can do it — he is ABLE." },
      { g: "Ἰορδάνης, -ου, ὁ", gloss: "the Jordan", freq: 15, tier: "memorize", icon: "🏞️", mn: "ee-or-THAH-nays ≈ \"YOUR-THAW-nays.\" Spelled Ἰορδ-, the JORDAN, its δ sounding \"th\"." },
      { g: "ἰσχυρός", gloss: "strong, mighty, powerful", freq: 29, tier: "memorize", icon: "💪", mn: "ees-KHEW-ros ≈ \"EES-KHEW-ros\" (rasped: kh). ἰσχύς is muscle — he muscles through: STRONG, mighty." },
      { g: "καθίζω", gloss: "I cause to sit down, appoint", freq: 46, tier: "memorize", icon: "🪑", mn: "kah-THEE-zo ≈ \"KATHY-EATS-oh.\" Kathy eats, so Kathy SITS DOWN." },
      { g: "κρατέω", gloss: "I grasp, hold (fast), arrest", freq: 47, tier: "memorize", icon: "✊", mn: "krah-TEH-o ≈ \"ka-RA-TE-o.\" KARATE is all grip and hold: I GRASP, HOLD FAST, ARREST." },
      { g: "μετάνοια, ἡ", gloss: "repentance", freq: 22, tier: "memorize", icon: "🔄", mn: "meh-tah-NEW-ah ≈ \"ME? a-NEW-ah!\" Me, made new — a changed mind: REPENTANCE." },
      { g: "ναός, ὁ", gloss: "temple, sanctuary", freq: 45, tier: "memorize", icon: "🏛️", mn: "nah-OS ≈ \"NOAH'S.\" Noah's holy house: the TEMPLE." },
      { g: "ὅμοιος", gloss: "like, similar", freq: 45, tier: "memorize", icon: "🟰", mn: "ho-MEW-os ≈ \"ho-MEW-os.\" The ὁμο- of HOMOgeneous — all of one kind: LIKE, similar." },
      { g: "ὀπίσω", gloss: "after, behind", freq: 35, tier: "memorize", icon: "👣", mn: "o-PEE-so ≈ \"OH-PEE-so.\" Opie tags along AFTER you, always BEHIND." },
      { g: "οὐαί", gloss: "woe", freq: 46, tier: "memorize", icon: "😱", mn: "oo-EH ≈ \"oo-AY!\" Said aloud it is already a wail: WOE!" },
      { g: "οὐκέτι", gloss: "no longer", freq: 47, tier: "memorize", icon: "🚫", mn: "oo-KEH-tee ≈ \"ooh-KETTLE.\" The kettle is NO LONGER boiling." },
      { g: "πειράζω", gloss: "I tempt, test", freq: 38, tier: "memorize", icon: "🎣", mn: "pee-RAH-zo ≈ \"PEER-RAH-zo.\" He peers at you to TEST you." },
      { g: "ποταμός, ὁ", gloss: "river", freq: 17, tier: "memorize", icon: "🌊", mn: "po-tah-MOS ≈ \"a-POT-o'-MOSS.\" It floats away down the RIVER." },
      { g: "πρό", gloss: "before, in front of, at (+ gen.)", freq: 47, tier: "memorize", icon: "⏪", mn: "PRO ≈ \"a PRO.\" The pro always goes BEFORE the rookie." },
      { g: "προσφέρω", gloss: "I bring to, offer", freq: 47, tier: "memorize", icon: "🎁", mn: "pros-FEH-ro ≈ \"PROS-FERRY-o.\" The pros ferry it over and OFFER it." },
      { g: "Σατανᾶς, -ᾶ, ὁ", gloss: "Satan", freq: 36, tier: "memorize", icon: "😈", mn: "sah-tah-NAHS ≈ \"SATAN-ahs.\" The accuser himself: SATAN." },
      { g: "σταυρόω", gloss: "I crucify", freq: 46, tier: "memorize", icon: "✝️", mn: "STAV-ro-o ≈ \"STOW-a-ROW-oh.\" They STOW him away on a row of timber: they CRUCIFY him." },
      { g: "τεσσεράκοντα", gloss: "forty", freq: 22, tier: "memorize", icon: "4️⃣", mn: "tehs-seh-rah-KON-tah ≈ \"TESS-and-SARAH-COUNT-ah.\" They count to FORTY." },
      { g: "φυλακή, ἡ", gloss: "watch, guard, prison", freq: 47, tier: "memorize", icon: "🔒", mn: "few-lah-KAY ≈ \"a-FEW-lo-KAY.\" A few locked away, Kay: PRISON, a GUARD." },
      { g: "χώρα, ἡ", gloss: "district, region", freq: 28, tier: "memorize", icon: "🗺️", mn: "KHO-rah ≈ \"CORA\" (rasped: kh). Cora owns the whole REGION." },
      // ---- Vocabulary to Recognize ----
      { g: "ἄγριος", gloss: "wild", freq: 3, tier: "recognize", icon: "🌿", mn: "AH-ghree-os ≈ \"ANGRY-os.\" Angry and untamed: WILD." },
      { g: "ἀκρίς, -ίδος, ἡ", gloss: "locust", freq: 4, tier: "recognize", icon: "🦗", mn: "ah-KREES ≈ \"a-CREASE.\" The locusts eat a crease across the field: LOCUST." },
      { g: "βοάω", gloss: "I call, shout, cry out", freq: 12, tier: "recognize", icon: "📣", mn: "vo-AH-o ≈ \"a VOW — AH — OH!\" Every syllable of it is a shout: he CRIES OUT." },
      { g: "δερμάτινος", gloss: "(made of) leather", freq: 2, tier: "recognize", icon: "🧥", mn: "thehr-mah-TEE-nos ≈ \"THERMAL-TEE-nos.\" Spelled δερμ-, our DERMATOLOGY — skin, so (made of) LEATHER." },
      { g: "ἐξομολογέω", gloss: "I confess, admit", freq: 10, tier: "recognize", icon: "🙏", mn: "ehx-o-mo-lo-GHEH-o ≈ \"EGGS-o-mo-lo-GAY-o.\" He logs it all out loud: CONFESS." },
      { g: "εὐθύς", gloss: "straight", freq: 8, tier: "recognize", icon: "📏", mn: "ev-THEWS ≈ \"EV — THOSE!\" Ev sends those STRAIGHT ahead." },
      { g: "ζώνη, ἡ", gloss: "belt", freq: 8, tier: "recognize", icon: "🎽", mn: "ZO-nay ≈ \"a ZONE-ay.\" The BELT is the zone around your waist." },
      { g: "Ἱεροσολυμίτης, -ου, ὁ", gloss: "inhabitant of Jerusalem", freq: 2, tier: "recognize", icon: "🏙️", mn: "hee-eh-ro-so-lew-MEE-tays ≈ \"HIERO-SO-LEW-mee-tays.\" A JERUSALEM-ite." },
      { g: "ἱμάς, -άντος, ὁ", gloss: "strap, thong", freq: 4, tier: "recognize", icon: "🪢", mn: "hee-MAHS ≈ \"HE-MASHED.\" He mashed the sandal STRAP flat." },
      { g: "κάμηλος, ὁ", gloss: "camel", freq: 6, tier: "recognize", icon: "🐪", mn: "kah-MAY-los ≈ \"ka-MAY-los.\" Say it and it is already the CAMEL." },
      { g: "κατασκευάζω", gloss: "I make ready, prepare", freq: 11, tier: "recognize", icon: "🔨", mn: "kah-tah-SKEV-ah-zo ≈ \"CUT-a-SKEV-a-zo.\" Cut it, skewer it, PREPARE the feast." },
      { g: "κύπτω", gloss: "I bend down", freq: 2, tier: "recognize", icon: "🙇", mn: "KEWP-to ≈ \"CUTE-P-toe\" — like \"cute\" with a P. He stoops low: BEND DOWN." },
      { g: "μέλι, -ιτος, τό", gloss: "honey", freq: 4, tier: "recognize", icon: "🍯", mn: "MEH-lee ≈ \"MEL-ee.\" Mel loves his HONEY." },
      { g: "Ναζαρέτ, ἡ", gloss: "Nazareth", freq: 12, tier: "recognize", icon: "🏘️", mn: "nah-zah-REHT ≈ \"NAZA-RET.\" The town itself: NAZARETH." },
      { g: "ὀσφῦς, ἡ", gloss: "waist", freq: 8, tier: "recognize", icon: "🧍", mn: "os-FEWS ≈ \"OS-FEWS.\" The few bones at your WAIST." },
      { g: "περιστερά, ἡ", gloss: "dove, pigeon", freq: 10, tier: "recognize", icon: "🕊️", mn: "peh-ree-steh-RAH ≈ \"PERRY'S-STAIR-ah.\" A DOVE settles on Perry's stair." },
      { g: "σχίζω", gloss: "I split, divide, separate, tear apart", freq: 11, tier: "recognize", icon: "✂️", mn: "SKHEE-zo ≈ \"SKIS-oh.\" The skis SPLIT the snow apart." },
      { g: "τρίβος, ἡ", gloss: "path", freq: 3, tier: "recognize", icon: "🛤️", mn: "TREE-vos ≈ \"TREE-VOSS.\" The PATH worn between the trees." },
      { g: "ὑπόδημα, -ατος, τό", gloss: "sandal", freq: 10, tier: "recognize", icon: "👡", mn: "hew-po-THAY-mah ≈ \"WHO-put-THEM-ah?\" The SANDALS, of course." }
    ]
  },
  {
    id: "gd-set-02",
    source: "Going Deeper with New Testament Greek",
    chapter: 3,
    title: "Chapter 3 — Romans Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀγρός, ὁ", gloss: "field, country", freq: 36, tier: "memorize", icon: "🌾", mn: "ah-GHROS ≈ \"a GROSS.\" A gross of wheat standing in the FIELD." },
      { g: "ἀκάθαρτος", gloss: "unclean, impure", freq: 32, tier: "memorize", icon: "🚱", mn: "ah-kah-THAHR-tos ≈ \"a-CATHARTIC-os.\" A cathartic cleanses — and the ἀ- cancels it: UNCLEAN." },
      { g: "ἀκροβυστία, ἡ", gloss: "uncircumcision", freq: 20, tier: "memorize", icon: "✂️", mn: "ah-kro-VEW-stee-ah ≈ \"ACRO-VEW-stee-ah.\" An ACROBAT keeps his ἄκρον, his tip, exactly as it was: UNCIRCUMCISION." },
      { g: "ἀναγινώσκω", gloss: "I read (aloud)", freq: 32, tier: "memorize", icon: "📖", mn: "ah-nah-ghee-NOS-ko ≈ \"ANNA-GHEE-KNOWS-ko.\" Anna knows her letters — she READS it aloud." },
      { g: "ἄνεμος, ὁ", gloss: "wind", freq: 31, tier: "memorize", icon: "🌬️", mn: "AH-neh-mos ≈ \"AH-neh-MOSS.\" It lifts the moss right off the stone — an ANEMOmeter measures it: the WIND." },
      { g: "ἀρνέομαι", gloss: "I deny, reject", freq: 33, tier: "memorize", icon: "🙅", mn: "ahr-NEH-o-meh ≈ \"ARE? NAY! — o-me.\" Asked, and he says nay: I DENY it." },
      { g: "βιβλίον, τό", gloss: "book, scroll", freq: 34, tier: "memorize", icon: "📕", mn: "veev-LEE-on ≈ \"VEEV-lee-on.\" Our word BIBLE, softened: the BOOK, the scroll." },
      { g: "διαθήκη, ἡ", gloss: "covenant, decree, last will and testament", freq: 33, tier: "memorize", icon: "📜", mn: "thee-ah-THAY-kay ≈ \"THEE-a-THAY-kay.\" διά between + τίθημι place — terms laid down between two parties: a COVENANT, a last will." },
      { g: "διακονία, ἡ", gloss: "service, office, ministry, deacon", freq: 34, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEE-ah ≈ \"THEE-a-CONE-ee-ah.\" The root of DEACON, its δ softened to \"th\": MINISTRY." },
      { g: "δικαιόω", gloss: "I justify, vindicate", freq: 39, tier: "memorize", icon: "⚖️", mn: "thee-KEH-o-o ≈ \"THEE? OKAY-o!\" Thee — okay, you are in the right. From δίκαιος: I JUSTIFY, I VINDICATE." },
      { g: "διότι", gloss: "for, because, therefore", freq: 23, tier: "memorize", icon: "➡️", mn: "thee-O-tee ≈ \"THEE-O-tee\" — you can hear THEO in it, God. Why did any of it happen? BECAUSE of him. For, because, therefore." },
      { g: "δυνατός", gloss: "powerful, strong, mighty, able", freq: 32, tier: "memorize", icon: "💪", mn: "thew-nah-TOS ≈ \"THEW-not-a-TOSS.\" Do NOT toss this one aside — spelled δυν-, our DYNAMITE: POWERFUL, able." },
      { g: "ἐγγύς", gloss: "near, close to", freq: 31, tier: "memorize", icon: "📍", mn: "ehng-GHEWS ≈ \"en-GOOSE.\" The goose is right there at your heel — NEAR, close to." },
      { g: "ἔξεστιν", gloss: "it is lawful, permitted", freq: 31, tier: "memorize", icon: "✅", mn: "ehx-eh-STEEN ≈ \"EX-EH-STEEN\" — all but EXISTING. It is lawful for this to exist: IT IS PERMITTED." },
      { g: "ἐπίγνωσις, -εως, ἡ", gloss: "knowledge, recognition", freq: 20, tier: "memorize", icon: "💡", mn: "eh-pee-ghno-SEES ≈ \"a-PIGGY-KNOWS-ees.\" What the piggy knows in full: KNOWLEDGE." },
      { g: "εὐθέως", gloss: "immediately", freq: 36, tier: "memorize", icon: "⚡", mn: "ev-THEH-os ≈ \"EV-THEH-os.\" εὐ- well + θέω run: run straight there and arrive IMMEDIATELY." },
      { g: "ἐχθρός", gloss: "hostile, hated", freq: 32, tier: "memorize", icon: "⚔️", mn: "ehkh-THROS ≈ \"EXTRA-GROSS.\" Extra gross to you: HOSTILE, hated." },
      { g: "ἥλιος, ὁ", gloss: "sun", freq: 32, tier: "memorize", icon: "☀️", mn: "HAY-lee-os ≈ \"HELIOS / HELIUM.\" Helium was found in the SUN." },
      { g: "ἱερεύς, -έως, ὁ", gloss: "priest", freq: 31, tier: "memorize", icon: "🕍", mn: "hee-eh-REVS ≈ \"HE-EVER-REVS.\" He ever revs the altar coals — ἱερός is holy: the PRIEST." },
      { g: "καθαρίζω", gloss: "I cleanse, purify", freq: 31, tier: "memorize", icon: "🧼", mn: "kah-thah-REE-zo ≈ \"CATHARSIS-o.\" Catharsis is a washing out: I CLEANSE." },
      { g: "καταργέω", gloss: "I cancel, nullify, make void", freq: 27, tier: "memorize", icon: "🚫", mn: "kah-tahr-GHEH-o ≈ \"ka-TAR-GHEH-o.\" A KARATE chop to it — κατά down + ἀργός idle: I CANCEL, MAKE VOID." },
      { g: "λογίζομαι", gloss: "I account, reckon, conclude", freq: 40, tier: "memorize", icon: "🧮", mn: "lo-GHEE-zo-meh ≈ \"lo-GEE-zo-may.\" Same root as LOGIC and LOGarithm — you tot it up: I RECKON, I ACCOUNT." },
      { g: "μέλος, -ους, τό", gloss: "member, part, limb", freq: 34, tier: "memorize", icon: "🦵", mn: "MEH-los ≈ \"ME-LOSS.\" Me, and the loss of a limb: a MEMBER, a part of the body." },
      { g: "ναί", gloss: "yes, certainly, indeed", freq: 33, tier: "memorize", icon: "👍", mn: "NEH ≈ \"NEH.\" Careful — it sounds like our \"nay\" but means the opposite: YES." },
      { g: "νυνί", gloss: "now", freq: 20, tier: "memorize", icon: "⏱️", mn: "new-NEE ≈ \"NEW-nee.\" What is new is what is NOW." },
      { g: "ὀργή, ἡ", gloss: "anger, wrath, punishment", freq: 36, tier: "memorize", icon: "😤", mn: "or-GHAY ≈ \"ORGY.\" An ORGY is what calls down the WRATH: ANGER, and the punishment after it." },
      { g: "οὖς, ὠτός, τό", gloss: "ear, hearing", freq: 36, tier: "memorize", icon: "👂", mn: "OOS ≈ \"OOZE.\" Cup it and listen — the EAR." },
      { g: "παραγίνομαι", gloss: "I come, arrive, appear", freq: 37, tier: "memorize", icon: "🛬", mn: "pah-rah-ghee-NO-meh ≈ \"PARA-GHEE-no-may.\" The PARAchute drops him in right beside you: I ARRIVE, I APPEAR." },
      { g: "παρρησία, ἡ", gloss: "confidence, boldness", freq: 31, tier: "memorize", icon: "🗣️", mn: "pahr-ray-SEE-ah ≈ \"PARTY-SIRI-ah.\" Ask Siri at the party — she answers anyone, out loud, no hesitation: BOLDNESS." },
      { g: "περιτομή, ἡ", gloss: "circumcision", freq: 36, tier: "memorize", icon: "✂️", mn: "peh-ree-to-MAY ≈ \"PERI-TOMY.\" Peri- is around, -tomy is a cut: CIRCUMCISION." },
      { g: "πλήν", gloss: "yet, however, but", freq: 31, tier: "memorize", icon: "↩️", mn: "PLAYN ≈ \"PLAY ON.\" Play on — YET, however, the score has changed." },
      { g: "ποῖος", gloss: "of what kind?", freq: 33, tier: "memorize", icon: "❓", mn: "PEW-os ≈ \"PYEH-os\" — close to Russian поезд, a train. WHAT KIND of train is this?" },
      { g: "ποτήριον, τό", gloss: "cup", freq: 31, tier: "memorize", icon: "🍷", mn: "po-TAY-ree-on ≈ \"POTTERY-on.\" Pottery is what the CUP is made of." },
      { g: "ποῦ", gloss: "where?", freq: 48, tier: "memorize", icon: "🧭", mn: "POO ≈ \"POO.\" WHERE did that come from?" },
      { g: "πτωχός", gloss: "poor", freq: 34, tier: "memorize", icon: "🪙", mn: "pto-KHOS ≈ \"p-TOE-KHOS\" (rasped: kh). Poor OJOS — eyes hollow from hunger: POOR, a beggar." },
      { g: "ὑποστρέφω", gloss: "I turn back, return", freq: 35, tier: "memorize", icon: "🔙", mn: "hew-po-STREH-fo ≈ \"HUE-po-STROPHE-o.\" A strophe is a turn — turn back: RETURN." },
      { g: "ὑστερέω", gloss: "I fall short of, lack", freq: 16, tier: "memorize", icon: "📉", mn: "hew-steh-REH-o ≈ \"HYSTER-eh-o.\" Hysteros is later — he came in last: I FALL SHORT." },
      { g: "φανερόω", gloss: "I reveal, make manifest, show", freq: 49, tier: "memorize", icon: "🔦", mn: "fah-neh-RO-o ≈ \"fa-NAR-o-o\" — Russian фонарь, a flashlight. Shine it and the thing is seen: I REVEAL." },
      { g: "Φίλιππος, ὁ", gloss: "Philip", freq: 36, tier: "memorize", icon: "🧑", mn: "FEE-leep-pos ≈ \"PHILIP with an F.\" Philip." },
      { g: "χωρίς", gloss: "without, apart from", freq: 41, tier: "memorize", icon: "➗", mn: "kho-REES ≈ \"WHO-REES.\" Who are you WITHOUT him? Apart from, without." },
      // ---- Vocabulary to Recognize (no built-in hook: these are pass-through) ----
      { g: "ἁμάρτημα, -ατος, τό", gloss: "sin, transgression", freq: 4, tier: "recognize" },
      { g: "ἀνοχή, ἡ", gloss: "forbearance, tolerance", freq: 2, tier: "recognize" },
      { g: "ἀπολύτρωσις, -εως, ἡ", gloss: "redemption, release, deliverance", freq: 10, tier: "recognize" },
      { g: "διαστολή, ἡ", gloss: "distinction, difference", freq: 3, tier: "recognize" },
      { g: "δωρεάν", gloss: "freely, as a gift, without payment", freq: 9, tier: "recognize" },
      { g: "εἴπερ", gloss: "if indeed, if perhaps", freq: 6, tier: "recognize" },
      { g: "ἐκκλείω", gloss: "I exclude, shut out", freq: 2, tier: "recognize" },
      { g: "ἔνδειξις, ἡ", gloss: "demonstration, proof", freq: 4, tier: "recognize" },
      { g: "ἱλαστήριον, τό", gloss: "propitiation", freq: 2, tier: "recognize" },
      { g: "καύχησις, ἡ", gloss: "boasting", freq: 11, tier: "recognize" },
      { g: "πάρεσις, ἡ", gloss: "passing over", freq: 1, tier: "recognize" },
      { g: "προγίνομαι", gloss: "it happens before, be done before", freq: 1, tier: "recognize" },
      { g: "προτίθημι", gloss: "I present, put forward, display publicly", freq: 3, tier: "recognize" },
      { g: "ὑπόδικος", gloss: "answerable, accountable", freq: 1, tier: "recognize" },
      { g: "φράσσω", gloss: "I shut, close", freq: 3, tier: "recognize" }
    ]
  },
  {
    id: "gd-set-03",
    source: "Going Deeper with New Testament Greek",
    chapter: 4,
    title: "Chapter 4 — Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀγοράζω", gloss: "I buy, purchase", freq: 30, tier: "memorize", icon: "🛒", mn: "ah-gho-RAH-zo ≈ \"the AGORA-zo.\" The ἀγορά is the marketplace — where you go to BUY." },
      { g: "ἀδικέω", gloss: "I do wrong, treat unjustly", freq: 28, tier: "memorize", icon: "⚖️", mn: "ah-thee-KEH-o ≈ \"ah-THEE-KAY-o.\" Ah, thee? Okay — and he hands you the short end of a rigged scale. ἀ- strips out the δίκη, the justice: I TREAT UNJUSTLY." },
      { g: "ἀληθινός", gloss: "true, real, genuine", freq: 28, tier: "memorize", icon: "💎", mn: "ah-lay-thee-NOS ≈ \"a-LAY-THEE-NOSE.\" Lay thee nose against it — no crack, no fake: GENUINE." },
      { g: "ἀνάγκη, ἡ", gloss: "necessity, pressure", freq: 17, tier: "memorize", icon: "⛓️", mn: "ah-NAHNG-kay ≈ \"a-NAG — KAY!\" A nag, Kay, that will not let up: NECESSITY, pressure." },
      { g: "ἅπαξ", gloss: "once and for all", freq: 14, tier: "memorize", icon: "1️⃣", mn: "HAH-pahx ≈ \"HA! — PACKS.\" He packs it away once, and never again: ONCE FOR ALL." },
      { g: "ἀρνίον, τό", gloss: "lamb, sheep", freq: 30, tier: "memorize", icon: "🐑", mn: "ahr-NEE-on ≈ \"ARE-KNEE-on.\" Down on your knees before the LAMB." },
      { g: "ἁρπάζω", gloss: "I grasp, snatch, seize", freq: 14, tier: "memorize", icon: "🫳", mn: "hahr-PAH-zo ≈ \"HARP-AH-zo.\" A harpy, and our HARPOON: it SNATCHES its prey." },
      { g: "Βαρναβᾶς, ὁ", gloss: "Barnabas", freq: 28, tier: "memorize", icon: "🤝", mn: "vahr-nah-VAHS ≈ \"VAR-na-VAHS.\" Both β's say \"v\" in Koine: BARNABAS." },
      { g: "γαμέω", gloss: "I marry", freq: 28, tier: "memorize", icon: "💍", mn: "ghah-MEH-o ≈ \"GAM-MAY-o.\" Gam — May! He asks for her hand in May: I MARRY. (Our monoGAMY.)" },
      { g: "γνῶσις, -εως, ἡ", gloss: "knowledge", freq: 29, tier: "memorize", icon: "🧠", mn: "GHNO-sees ≈ \"g-NO-SEES.\" An aGNOStic is one without it: KNOWLEDGE." },
      { g: "διακρίνω", gloss: "I discriminate, judge, doubt", freq: 19, tier: "memorize", icon: "🤔", mn: "thee-ah-KREE-no ≈ \"THEY-a-GREE? NO!\" Two witnesses, and they agree? No — so you sort out which one is telling it straight: I DISCRIMINATE, I JUDGE. When the two who disagree are both inside your own head, you DOUBT." },
      { g: "ἐλεέω", gloss: "I have mercy on", freq: 29, tier: "memorize", icon: "🙏", mn: "eh-leh-EH-o ≈ \"EL-eh-EH-o.\" Kyrie ELEISON — Lord, HAVE MERCY." },
      { g: "ἔλεος, -ους, τό", gloss: "mercy, compassion", freq: 27, tier: "memorize", icon: "💗", mn: "EH-leh-os ≈ \"ELL-eh-oss.\" The noun standing behind eleison: MERCY itself." },
      { g: "ἐπιθυμία, ἡ", gloss: "lust, craving, desire", freq: 39, tier: "memorize", icon: "🔥", mn: "eh-pee-thew-MEE-ah ≈ \"EPI(pen)-THEW-ME-ah.\" The craving comes on like a reaction, and only the EPIPEN jabbed into me will fix it: LUST, craving, DESIRE." },
      { g: "ἐπικαλέω", gloss: "I call (upon), name", freq: 30, tier: "memorize", icon: "📣", mn: "eh-pee-kah-LEH-o ≈ \"EPIC-a-LAY-o.\" An EPIC call, shouted over everyone’s head: I CALL UPON, I NAME." },
      { g: "ἐπιτιμάω", gloss: "I rebuke, reprove, warn", freq: 29, tier: "memorize", icon: "☝️", mn: "eh-pee-tee-MAH-o ≈ \"EPPIE-TEED-MA-off.\" Eppie teed Ma off, and she lets him have it on the doorstep: I REBUKE, reprove, WARN." },
      { g: "ἡγέομαι", gloss: "I lead, think, consider", freq: 28, tier: "memorize", icon: "🧭", mn: "hay-gheh-O-meh ≈ \"HAY-GO-may.\" Hay, go! — he is already out in front: I LEAD, and so I RECKON it best." },
      { g: "θυγάτηρ, -τρός, ἡ", gloss: "daughter, girl", freq: 28, tier: "memorize", icon: "👧", mn: "thew-GHAH-tayr ≈ \"THEW-GATOR.\" Daddy’s little GATOR, all teeth and trouble: the DAUGHTER." },
      { g: "θυσία, ἡ", gloss: "sacrifice, offering", freq: 28, tier: "memorize", icon: "🔥", mn: "thew-SEE-ah ≈ \"THEW-SEE-ya.\" One last see-ya as it goes up in smoke: the SACRIFICE, the offering." },
      { g: "Ἰάκωβος, ὁ", gloss: "James", freq: 42, tier: "memorize", icon: "🧔", mn: "ee-ah-KO-vos ≈ \"ee-a-CO-VOS.\" Jacob in Greek dress — which English turned into JAMES." },
      { g: "ἴδε", gloss: "look, see, behold", freq: 29, tier: "memorize", icon: "👀", mn: "EE-theh ≈ \"EE-ther\" — EITHER, said the American way. Either you look now or you miss him: LOOK! BEHOLD. (Spelled ἴδ-, the root under IDEA — a thing seen.)" },
      { g: "Ἰούδας, ὁ", gloss: "Jude, Judah, Judas", freq: 44, tier: "memorize", icon: "🪙", mn: "ee-OO-thahs ≈ \"ee-OO-THAHS.\" One name for all three: JUDAS, Jude, Judah." },
      { g: "Καῖσαρ, -αρος, ὁ", gloss: "Caesar, emperor", freq: 29, tier: "memorize", icon: "👑", mn: "KEH-sahr ≈ \"KAY-SAR.\" Not \"see-zer\" — Koine αι is \"eh\": CAESAR." },
      { g: "μάχαιρα, ἡ", gloss: "sword", freq: 29, tier: "memorize", icon: "🗡️", mn: "mah-KHEH-rah ≈ \"ma-KHEH-rah\" (rasped: kh). Russian махать, to wave — she waves the blade: the SWORD." },
      { g: "μιμνῄσκομαι", gloss: "I remember, recollect", freq: 23, tier: "memorize", icon: "🧵", mn: "meem-NAY-sko-meh ≈ \"meem-NAY-sko-may.\" The root of MNEMONIC itself — the whole point of these hooks: I REMEMBER." },
      { g: "μισέω", gloss: "I hate, detest", freq: 40, tier: "memorize", icon: "😠", mn: "mee-SEH-o ≈ \"ME-SAY-o.\" A MISanthrope says it of everyone: I HATE." },
      { g: "μισθός, ὁ", gloss: "pay, wages, reward", freq: 29, tier: "memorize", icon: "💵", mn: "mees-THOS ≈ \"MISS-THOSE.\" Miss those and you worked all day for nothing: PAY, WAGES, reward." },
      { g: "παράκλησις, -εως, ἡ", gloss: "encouragement, comfort", freq: 29, tier: "memorize", icon: "🫂", mn: "pah-rah-KLAY-sees ≈ \"PARA-CLAY-sees.\" The PARACLETE is called alongside you: COMFORT." },
      { g: "παρέρχομαι", gloss: "I pass by, neglect, disobey", freq: 29, tier: "memorize", icon: "🚶", mn: "pah-REHR-kho-meh ≈ \"pa-RARE-ko-may\" (rasped: kh). παρά alongside + ἔρχομαι come: I PASS BY." },
      { g: "πάσχα, τό", gloss: "Passover", freq: 29, tier: "memorize", icon: "🍷", mn: "PAHS-khah ≈ \"PAS-KHA.\" Pascha itself, barely changed: the PASSOVER." },
      { g: "ποτέ", gloss: "once, formerly, ever", freq: 29, tier: "memorize", icon: "🕰️", mn: "po-TEH ≈ \"po-TAY.\" \"Once upon a po-TAY\" — ONCE, formerly, ever." },
      { g: "σκανδαλίζω", gloss: "I cause to stumble", freq: 29, tier: "memorize", icon: "🪨", mn: "skahn-thah-LEE-zo ≈ \"SCAN-THAL-ee-zo.\" Spelled σκανδαλ-, our SCANDAL — Koine δ says \"th\": I MAKE THEM STUMBLE." },
      { g: "σκότος, -ους, τό", gloss: "darkness", freq: 31, tier: "memorize", icon: "🌑", mn: "SKO-tos ≈ \"SCO-TOSS.\" Toss the lamp out and this is what is left: DARKNESS." },
      { g: "συνείδησις, -εως, ἡ", gloss: "conscience", freq: 30, tier: "memorize", icon: "💭", mn: "sew-nee-THAY-sees ≈ \"SEW-knee-THEY-sees.\" σύν with + οἶδα know — knowing along with yourself: CONSCIENCE." },
      { g: "σωτήρ, -ῆρος, ὁ", gloss: "savior, deliverer", freq: 24, tier: "memorize", icon: "🛟", mn: "so-TAYR ≈ \"so-TARE.\" SOTERiology is the doctrine of him: the SAVIOR." },
      { g: "σωτηρία, ἡ", gloss: "salvation, deliverance", freq: 46, tier: "memorize", icon: "✝️", mn: "so-tay-REE-ah ≈ \"so-tay-REE-ah.\" What the σωτήρ brings with him: SALVATION." },
      { g: "φίλος", gloss: "beloved, friend", freq: 29, tier: "memorize", icon: "🫶", mn: "FEE-los ≈ \"FEEL-oss.\" PHILadelphia is love of the brother: a FRIEND, beloved." },
      { g: "φόβος, ὁ", gloss: "fear, reverence, respect", freq: 47, tier: "memorize", icon: "😨", mn: "FO-vos ≈ \"FOE-VOSS.\" Our PHOBIA — but here it can also mean reverence: FEAR." },
      { g: "φυλάσσω", gloss: "I guard, protect", freq: 31, tier: "memorize", icon: "🛡️", mn: "few-LAHS-so ≈ \"a-FEW-LASSO.\" A few lassos thrown round the flock: I GUARD." },
      { g: "φυλή, ἡ", gloss: "tribe, nation, people", freq: 31, tier: "memorize", icon: "🏕️", mn: "few-LAY ≈ \"a-FEW-LAY.\" A few lay claim to one bloodline: a TRIBE." },
      // ---- Vocabulary to Recognize ----
      // Read once and move on, so these carry no built-in hook.
      { g: "ἀγαλλίασις, ἡ", gloss: "exultation", freq: 5, tier: "recognize" },
      { g: "ἄμωμος", gloss: "blameless", freq: 8, tier: "recognize" },
      { g: "ἀποδιορίζω", gloss: "I divide, separate", freq: 1, tier: "recognize" },
      { g: "ἄπταιστος", gloss: "without stumbling", freq: 1, tier: "recognize" },
      { g: "ἀσέβεια, ἡ", gloss: "impiety", freq: 6, tier: "recognize" },
      { g: "ἐλεάω", gloss: "I have mercy on", freq: 3, tier: "recognize" },
      { g: "ἐμπαίκτης, -ου, ὁ", gloss: "mocker", freq: 2, tier: "recognize" },
      { g: "ἐπαγωνίζομαι", gloss: "I contend", freq: 1, tier: "recognize" },
      { g: "ἐποικοδομέω", gloss: "I edify, build up/on", freq: 7, tier: "recognize" },
      { g: "κατενώπιον", gloss: "opposite, in the presence of", freq: 3, tier: "recognize" },
      { g: "κλητός", gloss: "called, invited", freq: 10, tier: "recognize" },
      { g: "κοινός", gloss: "communal, common", freq: 14, tier: "recognize" },
      { g: "κράτος, τό", gloss: "power, rule", freq: 12, tier: "recognize" },
      { g: "μεγαλωσύνη, ἡ", gloss: "majesty", freq: 3, tier: "recognize" },
      { g: "πληθύνω", gloss: "I multiply, grow, increase", freq: 12, tier: "recognize" },
      { g: "προλέγω", gloss: "I foretell, proclaim beforehand", freq: 12, tier: "recognize" },
      { g: "προσδέχομαι", gloss: "I wait for", freq: 14, tier: "recognize" },
      { g: "σπιλόω", gloss: "I stain, defile", freq: 2, tier: "recognize" },
      { g: "σπουδή, ἡ", gloss: "eagerness, earnestness, diligence", freq: 12, tier: "recognize" },
      { g: "χιτών, -ῶνος, ὁ", gloss: "garment, shirt", freq: 11, tier: "recognize" },
      { g: "ψυχικός", gloss: "natural, unspiritual, worldly", freq: 6, tier: "recognize" },
    ]
  },
  {
    id: "gd-set-04",
    source: "Going Deeper with New Testament Greek",
    chapter: 5,
    title: "Chapter 5 — Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀδικία, ἡ", gloss: "unrighteousness, injustice", freq: 25, tier: "memorize", icon: "⚖️", mn: "ah-thee-KEE-ah ≈ \"a-THEE-KEY-ah.\" ἀ- not + δίκη justice, Koine δ as \"th\": INJUSTICE." },
      { g: "ἀληθής", gloss: "true, honest, genuine", freq: 26, tier: "memorize", icon: "✔️", mn: "ah-lay-THAYS ≈ \"a-LAY-THAYS.\" Lay it out and nothing is hidden: TRUE, honest." },
      { g: "ἀναβλέπω", gloss: "I look up, see again, receive sight", freq: 25, tier: "memorize", icon: "👁️", mn: "ah-nah-VLEH-po ≈ \"ANNA-VLEP-o.\" ἀνά up + βλέπω see: I LOOK UP — and the blind SEE AGAIN." },
      { g: "ἄρτι", gloss: "now", freq: 36, tier: "memorize", icon: "⏱️", mn: "AHR-tee ≈ \"ARTY.\" The arty crowd care about nothing but NOW." },
      { g: "ἀσθενής", gloss: "weak, powerless, sick", freq: 26, tier: "memorize", icon: "🤒", mn: "ahs-theh-NAYS ≈ \"as-THEN-AYS.\" Our ASTHENIA, without strength: WEAK, sick." },
      { g: "βαστάζω", gloss: "I bear, endure", freq: 27, tier: "memorize", icon: "🎒", mn: "vahs-TAH-zo ≈ \"VAS-TAH-zo.\" Spelled βαστ- but Koine β says \"v\": he hoists the vase and BEARS it." },
      { g: "γάμος, ὁ", gloss: "wedding, marriage", freq: 16, tier: "memorize", icon: "💒", mn: "GHAH-mos ≈ \"GAM-oss.\" MonoGAMy is one of these: a MARRIAGE." },
      { g: "γέ", gloss: "indeed, even", freq: 25, tier: "memorize", icon: "❗", mn: "GHEH ≈ \"GEH\" (hard g). One breath of emphasis and no more: INDEED." },
      { g: "γεύομαι", gloss: "I taste, experience", freq: 15, tier: "memorize", icon: "👅", mn: "GHEV-o-meh ≈ \"GAV-o-may.\" Gav gave me a spoonful to TASTE." },
      { g: "γνωρίζω", gloss: "I make known, reveal, know", freq: 25, tier: "memorize", icon: "📣", mn: "ghno-REE-zo ≈ \"g-NO-REE-zo.\" Built on γνῶσις, knowledge: I MAKE IT KNOWN." },
      { g: "δέκα", gloss: "ten", freq: 25, tier: "memorize", icon: "🔟", mn: "THEH-kah ≈ \"THECK-ah.\" Our DECAthlon and DECAde — Koine δ says \"th\": TEN." },
      { g: "δένδρον, τό", gloss: "tree", freq: 25, tier: "memorize", icon: "🌳", mn: "THEHN-thron ≈ \"THEN-THRON.\" A rhoDODENDRon is a rose-TREE." },
      { g: "διάκονος, ὁ", gloss: "servant, deacon", freq: 29, tier: "memorize", icon: "🍽️", mn: "thee-AH-ko-nos ≈ \"THEE-A-ko-nos.\" Spelled δια-, our DEACON: a SERVANT." },
      { g: "δουλεύω", gloss: "I am a slave, serve, obey", freq: 25, tier: "memorize", icon: "⛓️", mn: "thoo-LEV-o ≈ \"THOO-LEV-o.\" A δοῦλος is a slave, and this is his life: I SERVE." },
      { g: "ἐκχέω", gloss: "I pour out, shed", freq: 27, tier: "memorize", icon: "🫗", mn: "ehk-KHEH-o ≈ \"eck-KAY-o\" (rasped: kh). ἐκ out + χέω pour: I POUR IT OUT." },
      { g: "Ἕλλην, -ηνος, ὁ", gloss: "a Greek, gentile, pagan", freq: 25, tier: "memorize", icon: "🏛️", mn: "HEHL-layn ≈ \"HELL-ayn.\" HELLENistic is named for him: a GREEK." },
      { g: "ἕνεκα", gloss: "because of, on account of, for the sake of", freq: 26, tier: "memorize", icon: "➡️", mn: "HEH-neh-kah ≈ \"HEN-eh-ka.\" All this fuss on account of one hen: BECAUSE OF." },
      { g: "ἥκω", gloss: "I have come", freq: 26, tier: "memorize", icon: "🚪", mn: "HAY-ko ≈ \"HAY-ko.\" Hay-ho — I HAVE COME." },
      { g: "Ἰακώβ, ὁ", gloss: "Jacob", freq: 27, tier: "memorize", icon: "🪜", mn: "ee-ah-KOV ≈ \"ee-a-COV.\" The Hebrew form left undressed: JACOB." },
      { g: "καθαρός", gloss: "clean, pure", freq: 27, tier: "memorize", icon: "🫧", mn: "kah-thah-ROS ≈ \"ka-THA-ROSE.\" A CATHARtic leaves you CLEAN, pure." },
      { g: "κεῖμαι", gloss: "I lie, recline", freq: 24, tier: "memorize", icon: "🛏️", mn: "KEE-meh ≈ \"KEY-may.\" The key may just LIE there where it fell." },
      { g: "λυπέω", gloss: "I grieve, offend", freq: 26, tier: "memorize", icon: "😢", mn: "lew-PEH-o ≈ \"LOO-PAY-o.\" Loo, pay up — and it GRIEVES you." },
      { g: "Μαρία, ἡ", gloss: "Mary", freq: 27, tier: "memorize", icon: "👩", mn: "mah-REE-ah ≈ \"ma-REE-ah.\" The Greek spelling: MARY." },
      { g: "Μαριάμ, ἡ", gloss: "Mary", freq: 27, tier: "memorize", icon: "👩", mn: "mah-ree-AHM ≈ \"ma-ree-AHM.\" The Hebrew spelling of the same name: MARY." },
      { g: "μυστήριον, τό", gloss: "mystery, secret", freq: 28, tier: "memorize", icon: "🔐", mn: "mews-TAY-ree-on ≈ \"MUSE-TAY-ree-on.\" Straight across into English: MYSTERY." },
      { g: "νικάω", gloss: "I conquer, overcome", freq: 28, tier: "memorize", icon: "🏆", mn: "nee-KAH-o ≈ \"NIKE-ah-o.\" NIKE is victory herself: I CONQUER." },
      { g: "νυμφίος, ὁ", gloss: "bridegroom", freq: 16, tier: "memorize", icon: "🤵", mn: "newm-FEE-os ≈ \"NUMF-EE-os.\" The NYMPH is the bride; this is her man: the BRIDEGROOM." },
      { g: "οἶνος, ὁ", gloss: "wine", freq: 34, tier: "memorize", icon: "🍷", mn: "EW-nos ≈ \"EW-nos.\" Koine οι says \"ew\"; our OENOlogy is the study of WINE." },
      { g: "πνευματικός", gloss: "spiritual", freq: 26, tier: "memorize", icon: "🕊️", mn: "pnev-mah-tee-KOS ≈ \"p-NEV-ma-TEE-kos.\" πνεῦμα is breath and spirit — PNEUMAtic: SPIRITUAL." },
      { g: "πόθεν", gloss: "from where?", freq: 29, tier: "memorize", icon: "🧭", mn: "PO-thehn ≈ \"PO-THEN.\" Po — then where did it come from? FROM WHERE?" },
      { g: "πόσος", gloss: "how great/much/many (?)", freq: 27, tier: "memorize", icon: "📏", mn: "PO-sos ≈ \"PO-SOS.\" An SOS always asks HOW MUCH is left." },
      { g: "προφητεύω", gloss: "I prophesy", freq: 28, tier: "memorize", icon: "📜", mn: "pro-fay-TEV-o ≈ \"pro-fay-TEV-o.\" Say it aloud and it is already the word: I PROPHESY." },
      { g: "σός", gloss: "your", freq: 27, tier: "memorize", icon: "🫵", mn: "SOS ≈ \"SOSS.\" Short, blunt and possessive: YOUR." },
      { g: "σταυρός, ὁ", gloss: "cross", freq: 27, tier: "memorize", icon: "✝️", mn: "stav-ROS ≈ \"STAV-ROSE.\" The noun behind σταυρόω, and a stave of wood: the CROSS." },
      { g: "στρατιώτης, -ου, ὁ", gloss: "soldier", freq: 26, tier: "memorize", icon: "🪖", mn: "strah-tee-O-tays ≈ \"STRAT-ee-O-tays.\" STRATegy is his trade: a SOLDIER." },
      { g: "συνίημι", gloss: "I understand, comprehend", freq: 26, tier: "memorize", icon: "💡", mn: "sew-NEE-ay-mee ≈ \"SEW-KNEE-ay-me.\" σύν together + ἵημι send: you put it together and UNDERSTAND." },
      { g: "τελέω", gloss: "I finish, complete", freq: 28, tier: "memorize", icon: "🏁", mn: "teh-LEH-o ≈ \"TELL-AY-o.\" τέλος is the end — tell them it is FINISHED." },
      { g: "φρονέω", gloss: "I think, ponder", freq: 26, tier: "memorize", icon: "🤔", mn: "fro-NEH-o ≈ \"FRO-NAY-o.\" SchizoPHRENia splits this very thing: the mind — I THINK." },
      { g: "φωνέω", gloss: "I call", freq: 43, tier: "memorize", icon: "📞", mn: "fo-NEH-o ≈ \"FONE-AY-o.\" A phone exists for exactly this: I CALL." },
      { g: "χήρα, ἡ", gloss: "widow", freq: 26, tier: "memorize", icon: "🕯️", mn: "KHAY-rah ≈ \"KAY-rah\" (rasped: kh). Kay, left on her own now: the WIDOW." },
      // ---- Vocabulary to Recognize ----
      // Read once and move on, so these carry no built-in hook.
      { g: "ἀνά", gloss: "each", freq: 13, tier: "recognize" },
      { g: "ἀντλέω", gloss: "I draw (water)", freq: 4, tier: "recognize" },
      { g: "ἄνω", gloss: "above", freq: 9, tier: "recognize" },
      { g: "ἀρχιτρίκλινος, ὁ", gloss: "headwaiter", freq: 3, tier: "recognize" },
      { g: "γεμίζω", gloss: "I fill", freq: 8, tier: "recognize" },
      { g: "ἐλάσσων", gloss: "inferior, of lesser quality", freq: 4, tier: "recognize" },
      { g: "ἕξ", gloss: "six", freq: 13, tier: "recognize" },
      { g: "καθαρισμός, ὁ", gloss: "purification", freq: 7, tier: "recognize" },
      { g: "Κανά, ἡ", gloss: "Cana", freq: 4, tier: "recognize" },
      { g: "λίθινος", gloss: "(made of) stone", freq: 3, tier: "recognize" },
      { g: "μεθύσκω", gloss: "I get drunk", freq: 5, tier: "recognize" },
      { g: "μετρητής, -οῦ, ὁ", gloss: "measure", freq: 1, tier: "recognize" },
      { g: "ὑδρία, ἡ", gloss: "water jar", freq: 3, tier: "recognize" },
      { g: "χωρέω", gloss: "I contain", freq: 10, tier: "recognize" },
    ]
  },
  {
    id: "gd-set-05",
    source: "Going Deeper with New Testament Greek",
    chapter: 6,
    title: "Chapter 6 — Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἁμαρτωλός, ὁ", gloss: "sinner", freq: 47, tier: "memorize", icon: "🙇", mn: "hah-mahr-to-LOS ≈ \"ha-MAR-to-LOSS.\" He marred it, and it is his loss — ἁμαρτία is missing the mark: a SINNER." },
      { g: "ἀμπελών, -ῶνος, ὁ", gloss: "vineyard", freq: 23, tier: "memorize", icon: "🍇", mn: "ahm-peh-LON ≈ \"AMPLE-LAWN.\" An ample lawn of vines: the VINEYARD." },
      { g: "ἀνάγω", gloss: "I lead up, restore", freq: 23, tier: "memorize", icon: "⛰️", mn: "ah-NAH-gho ≈ \"a-NA-go.\" ἀνά up + ἄγω lead: I LEAD UP, I bring back — and at sea, I set sail." },
      { g: "ἀναιρέω", gloss: "I take away, destroy, kill", freq: 24, tier: "memorize", icon: "🗡️", mn: "ah-neh-REH-o ≈ \"a-NAIR-AY-o.\" ἀνά up + αἱρέω take — he takes it up and away for good: I DESTROY, I KILL." },
      { g: "ἄπιστος", gloss: "faithless, unbelieving", freq: 23, tier: "memorize", icon: "🚫", mn: "AH-pees-tos ≈ \"AH-PEACE-toss.\" Peace tossed out — ἀ- not + πίστις faith: FAITHLESS, unbelieving." },
      { g: "ἀσθένεια, ἡ", gloss: "weakness, sickness, disease", freq: 24, tier: "memorize", icon: "🤒", mn: "ahs-THEH-nee-ah ≈ \"as-THEN-ee-ah.\" Our ASTHENIA: WEAKNESS, sickness." },
      { g: "ἀσθενέω", gloss: "I am weak, sick, in need", freq: 33, tier: "memorize", icon: "🛌", mn: "ahs-theh-NEH-o ≈ \"as-THEN-AY-o.\" The verb of the same root: I AM WEAK, sick, in need." },
      { g: "ἀστήρ, -έρος, ὁ", gloss: "star", freq: 24, tier: "memorize", icon: "⭐", mn: "ahs-TAYR ≈ \"a-STARE.\" You stare up at it — and it is our ASTERisk: a STAR." },
      { g: "αὐξάνω", gloss: "I grow, increase", freq: 23, tier: "memorize", icon: "🌱", mn: "av-XAH-no ≈ \"av-ZA-no.\" Our AUGment and AUXiliary, both added on: I GROW, INCREASE." },
      { g: "δέησις, -εως, ἡ", gloss: "prayer, entreaty, petition", freq: 18, tier: "memorize", icon: "🙏", mn: "theh-AY-sees ≈ \"the-A-sees.\" The one who sees the need is asked: a PETITION, an entreaty." },
      { g: "εἰκών, -όνος, ἡ", gloss: "image, likeness, form", freq: 23, tier: "memorize", icon: "🖼️", mn: "ee-KON ≈ \"ee-CON.\" An ICON is exactly this: an IMAGE, a likeness." },
      { g: "ἐλεύθερος", gloss: "free", freq: 23, tier: "memorize", icon: "🕊️", mn: "eh-LEV-theh-ros ≈ \"a-LEV-thuh-ros.\" No chain on him at all: FREE." },
      { g: "ἐνεργέω", gloss: "I work, produce", freq: 21, tier: "memorize", icon: "⚡", mn: "eh-nehr-GHEH-o ≈ \"en-ER-GAY-o.\" Our ENERGY, put to use: I WORK, I PRODUCE." },
      { g: "ἑορτή, ἡ", gloss: "festival", freq: 25, tier: "memorize", icon: "🎉", mn: "heh-or-TAY ≈ \"he-or-TAY.\" Hey, or tay — everyone is out dancing: the FESTIVAL." },
      { g: "ἐπιστολή, ἡ", gloss: "letter, epistle", freq: 24, tier: "memorize", icon: "✉️", mn: "eh-pees-to-LAY ≈ \"a-PIS-to-LAY.\" Our EPISTLE, laid in your hand: a LETTER." },
      { g: "ἐπιστρέφω", gloss: "I turn (around/back), return", freq: 36, tier: "memorize", icon: "↩️", mn: "eh-pees-TREH-fo ≈ \"a-PIECE-TREF-o.\" ἐπί upon + στρέφω turn: I TURN AROUND, I RETURN." },
      { g: "Ἠλίας, ὁ", gloss: "Elijah", freq: 29, tier: "memorize", icon: "🔥", mn: "ay-LEE-ahs ≈ \"ay-LEE-as.\" Say it and the prophet is already there: ELIJAH." },
      { g: "ἰάομαι", gloss: "I heal, cure, restore", freq: 26, tier: "memorize", icon: "🩹", mn: "ee-AH-o-meh ≈ \"ee-AH-o-may.\" Our PSYCHIATRy and PEDIATRics hold this root: I HEAL, I CURE." },
      { g: "ἰσχύω", gloss: "I am strong, powerful, able", freq: 28, tier: "memorize", icon: "💪", mn: "ees-KHEW-o ≈ \"EES-KHEW-o\" (rasped: kh). The verb beside ἰσχυρός: I AM STRONG, I am able." },
      { g: "καταλείπω", gloss: "I leave (behind), abandon, neglect", freq: 24, tier: "memorize", icon: "🚪", mn: "kah-tah-LEE-po ≈ \"ka-ta-LEAP-o.\" He leaps away and it stays where it fell: I LEAVE BEHIND, abandon." },
      { g: "κελεύω", gloss: "I command, order, urge", freq: 25, tier: "memorize", icon: "📣", mn: "keh-LEV-o ≈ \"ke-LEV-o.\" He levels an order at you: I COMMAND, I ORDER." },
      { g: "κρίσις, -εως, ἡ", gloss: "judgment, condemnation", freq: 47, tier: "memorize", icon: "⚖️", mn: "KREE-sees ≈ \"CRISIS.\" A CRISIS is the moment of decision — and here the verdict: JUDGMENT." },
      { g: "λευκός", gloss: "white, bright, shining", freq: 25, tier: "memorize", icon: "🤍", mn: "lev-KOS ≈ \"LEV-KOSS.\" LEUKemia is named for the white cells: WHITE, shining." },
      { g: "μανθάνω", gloss: "I learn", freq: 25, tier: "memorize", icon: "📚", mn: "mahn-THAH-no ≈ \"man-THA-no.\" A MATHematician was first simply a learner: I LEARN." },
      { g: "μήν, -ος, ὁ", gloss: "month, new moon", freq: 18, tier: "memorize", icon: "🌙", mn: "MAYN ≈ \"MAIN.\" The main measure of a MONTH is the new moon." },
      { g: "μήποτε", gloss: "never, lest", freq: 25, tier: "memorize", icon: "🚷", mn: "MAY-po-teh ≈ \"MAY-po-tay.\" May it not, ever — NEVER; LEST it happen." },
      { g: "μήτε", gloss: "and not, nor", freq: 34, tier: "memorize", icon: "➖", mn: "MAY-teh ≈ \"MAY-tay.\" May-tay, nor this either: AND NOT, NOR." },
      { g: "νεφέλη, ἡ", gloss: "cloud", freq: 25, tier: "memorize", icon: "☁️", mn: "neh-FEH-lay ≈ \"ne-FELL-ay.\" NEBULous, and the rain fell from it: a CLOUD." },
      { g: "νοῦς, νοός, ὁ", gloss: "mind, understanding", freq: 24, tier: "memorize", icon: "🧠", mn: "NOOS ≈ \"NOOSE.\" A noose around your thinking — and the νοῦς is the MIND itself." },
      { g: "ὀμνύω", gloss: "I swear, take an oath", freq: 26, tier: "memorize", icon: "✋", mn: "om-NEW-o ≈ \"om-NEW-o.\" He starts over with a new vow: I SWEAR, I take an OATH." },
      { g: "παῖς, παιδός, ὁ/ἡ", gloss: "boy, child, son, servant", freq: 24, tier: "memorize", icon: "👦", mn: "PEHS ≈ \"PACE.\" PEDiatrics and PEDagogue are both built on him: the CHILD, the servant." },
      { g: "πάρειμι", gloss: "I am present, have come", freq: 24, tier: "memorize", icon: "📍", mn: "PAH-ree-mee ≈ \"PA-ree-me.\" παρά beside + εἰμί I am: I AM PRESENT, I have come." },
      { g: "παρουσία, ἡ", gloss: "coming, arrival", freq: 24, tier: "memorize", icon: "👑", mn: "pah-roo-SEE-ah ≈ \"pa-roo-SEE-ah.\" The PAROUSIA itself — his ARRIVAL, his coming." },
      { g: "πίμπλημι", gloss: "I fill, fulfill", freq: 24, tier: "memorize", icon: "🥛", mn: "PEEM-play-mee ≈ \"PIMP-LAY-me.\" Fill it to the brim and lay it down: I FILL, I FULFILL." },
      { g: "πλῆθος, -ους, τό", gloss: "multitude, large amount, crowd", freq: 31, tier: "memorize", icon: "👥", mn: "PLAY-thos ≈ \"PLAY-thoss.\" PLETHOra is our word for it: a MULTITUDE, a crowd." },
      { g: "πορνεία, ἡ", gloss: "(sexual) immorality", freq: 25, tier: "memorize", icon: "⛔", mn: "por-NEE-ah ≈ \"por-NEE-ah.\" PORNography is named from it: sexual IMMORALITY." },
      { g: "προσευχή, ἡ", gloss: "prayer", freq: 36, tier: "memorize", icon: "🙏", mn: "pro-sev-KHAY ≈ \"pro-sev-KHAY\" (rasped: kh). πρός toward + εὐχή vow — turned toward God: PRAYER." },
      { g: "προσέχω", gloss: "I pay attention to, devote myself to", freq: 24, tier: "memorize", icon: "👁️", mn: "pro-SEH-kho ≈ \"pro-SEK-o\" (rasped: kh). πρός toward + ἔχω hold — hold your mind toward it: I PAY ATTENTION." },
      { g: "προσκαλέω", gloss: "I summon, call, invite", freq: 29, tier: "memorize", icon: "📞", mn: "pros-kah-LEH-o ≈ \"pros-ka-LAY-o.\" πρός toward + καλέω call: I CALL YOU OVER, I SUMMON." },
      { g: "Τιμόθεος, ὁ", gloss: "Timothy", freq: 24, tier: "memorize", icon: "🧑", mn: "tee-MO-theh-os ≈ \"tee-MO-the-os.\" τιμή honour + θεός God — one who honours God: TIMOTHY." },
      // ---- Vocabulary to Recognize ----
      // ἕξ and ἐξομολογέω are printed here too, but are already in
      // earlier chapters, so they are not repeated as new entries.
      { g: "ἀλείφω", gloss: "I anoint", freq: 9, tier: "recognize" },
      { g: "βλαστάνω", gloss: "I produce, sprout", freq: 4, tier: "recognize" },
      { g: "βρέχω", gloss: "it rains (impers.); I send rain", freq: 7, tier: "recognize" },
      { g: "ἔλαιον, τό", gloss: "(olive) oil", freq: 11, tier: "recognize" },
      { g: "ἐνιαυτός, ὁ", gloss: "year, era", freq: 14, tier: "recognize" },
      { g: "εὐθυμέω", gloss: "I am cheerful", freq: 3, tier: "recognize" },
      { g: "εὐχή, ἡ", gloss: "prayer, oath, vow", freq: 3, tier: "recognize" },
      { g: "εὔχομαι", gloss: "I pray, wish", freq: 7, tier: "recognize" },
      { g: "κακοπαθέω", gloss: "I suffer hardship", freq: 3, tier: "recognize" },
      { g: "καλύπτω", gloss: "I cover, hide, conceal", freq: 8, tier: "recognize" },
      { g: "κάμνω", gloss: "I am weary, ill", freq: 2, tier: "recognize" },
      { g: "ὁμοιοπαθής, -ες", gloss: "with the same nature, like in every way", freq: 2, tier: "recognize" },
      { g: "ὅρκος, ὁ", gloss: "oath", freq: 10, tier: "recognize" },
      { g: "πλάνη, ἡ", gloss: "wandering, error, deception", freq: 10, tier: "recognize" },
      { g: "ὑετός, ὁ", gloss: "rain", freq: 5, tier: "recognize" },
      { g: "ψάλλω", gloss: "I sing (praise), make melody", freq: 5, tier: "recognize" },
    ]
  }
];

// Sentences built from each chapter's words, so they can be met in context
// rather than one at a time. Composed for this app, not quoted from the NT.
const SENTENCE_SETS = [
  { chapter: 2, items: [
    { g: "Ἰωάννης ἀπαγγέλλει βάπτισμα μετανοίας εἰς ἄφεσιν.", e: "John announces a baptism of repentance for forgiveness.", uses: ["ἀπαγγέλλω", "βάπτισμα", "μετάνοια", "ἄφεσις"] },
    { g: "ἐκπορεύεται ὁ ὄχλος εἰς τὴν ἔρημον πρὸς τὸν Ἰορδάνην ποταμόν.", e: "The crowd goes out into the desert, to the Jordan river.", uses: ["ἐκπορεύομαι", "ἔρημος", "Ἰορδάνης", "ποταμός"] },
    { g: "ἐνδύεται τρίχας καμήλου· ἰσχυρὸς δὲ ἔρχεται ὀπίσω αὐτοῦ.", e: "He wears camel's hair; but a strong one comes after him.", uses: ["ἐνδύω", "θρίξ", "ἰσχυρός", "ὀπίσω"] },
    { g: "τεσσεράκοντα ἡμέρας ὁ Σατανᾶς πειράζει αὐτὸν μετὰ τῶν θηρίων.", e: "For forty days Satan tempts him, among the wild animals.", uses: ["τεσσεράκοντα", "Σατανᾶς", "πειράζω", "θηρίον"] },
    { g: "πρὸ τοῦ προσώπου σου ἑτοιμάζω τὴν ὁδόν· διέρχεται γὰρ ὅλην τὴν χώραν.", e: "Before your face I prepare the way, for he goes through the whole region.", uses: ["πρό", "ἑτοιμάζω", "διέρχομαι", "χώρα"] },
    { g: "κρατοῦσιν αὐτὸν καὶ εἰς φυλακὴν ἄγουσιν· μεγάλη ἡ θλῖψις, καὶ οὐκέτι λαλεῖ.", e: "They seize him and lead him to prison; the affliction is great, and he speaks no longer.", uses: ["κρατέω", "φυλακή", "θλῖψις", "οὐκέτι"] },
    { g: "ὁ θεὸς εὐδοκεῖ, καθὼς Ἠσαΐας λέγει· καθίζει ὁ υἱὸς ἐν τῷ ναῷ.", e: "God is well pleased, as Isaiah says; the son sits down in the temple.", uses: ["εὐδοκέω", "Ἠσαΐας", "καθίζω", "ναός"] },
    { g: "οὐαί· σταυροῦσιν αὐτόν. ἄρα ἀποδίδωσιν ὁ θεὸς ἑκάστῳ.", e: "Woe — they crucify him. So then God repays each one.", uses: ["οὐαί", "σταυρόω", "ἄρα", "ἀποδίδωμι"] },
    { g: "οὐκ εἰμὶ ἱκανός, ἀλλὰ διακονῶ καὶ προσφέρω δῶρα, καὶ ἐπιγινώσκω αὐτόν.", e: "I am not qualified, but I serve and bring gifts, and I recognize him.", uses: ["ἱκανός", "διακονέω", "προσφέρω", "ἐπιγινώσκω"] },
    { g: "ἄχρι τοῦ δευτέρου ἔτους ὅμοιος ἦν τῷ πατρί.", e: "Until the second year he was like his father.", uses: ["ἄχρι", "δεύτερος", "ἔτος", "ὅμοιος"] },
  ] },
  { chapter: 3, items: [
    { g: "ἀναγινώσκει τὸ βιβλίον τῆς διαθήκης εἰς ἐπίγνωσιν ἀληθείας.", e: "He reads the book of the covenant, for knowledge of truth.", uses: ["ἀναγινώσκω", "βιβλίον", "διαθήκη", "ἐπίγνωσις"] },
    { g: "εὐθέως ὁ ἥλιος ἀνατέλλει καὶ ὁ ἄνεμος πνεῖ ἐπὶ τὸν ἀγρόν.", e: "Immediately the sun rises and the wind blows over the field.", uses: ["εὐθέως", "ἥλιος", "ἄνεμος", "ἀγρός"] },
    { g: "ὁ ἱερεὺς καθαρίζει τὸ ἀκάθαρτον ποτήριον.", e: "The priest cleanses the unclean cup.", uses: ["ἱερεύς", "καθαρίζω", "ἀκάθαρτος", "ποτήριον"] },
    { g: "χωρὶς περιτομῆς, ἐν ἀκροβυστίᾳ, δικαιοῖ ὁ θεός.", e: "Apart from circumcision, in uncircumcision, God justifies.", uses: ["χωρίς", "περιτομή", "ἀκροβυστία", "δικαιόω"] },
    { g: "ναί, νυνὶ λογίζομαι ταῦτα μετὰ παρρησίας.", e: "Yes, now I reckon these things with boldness.", uses: ["ναί", "νυνί", "λογίζομαι", "παρρησία"] },
    { g: "ὁ πτωχὸς ὑστερεῖ· ἔξεστιν οὖν διακονίαν ποιεῖν αὐτῷ.", e: "The poor man lacks; so it is lawful to do him service.", uses: ["πτωχός", "ὑστερέω", "ἔξεστιν", "διακονία"] },
    { g: "ὁ δυνατὸς καταργεῖ τὸν ἐχθρὸν καὶ τὴν ὀργήν.", e: "The mighty one nullifies the enemy and the wrath.", uses: ["δυνατός", "καταργέω", "ἐχθρός", "ὀργή"] },
    { g: "Φίλιππος παραγίνεται ἐγγὺς καὶ ὑποστρέφει.", e: "Philip arrives nearby and turns back.", uses: ["Φίλιππος", "παραγίνομαι", "ἐγγύς", "ὑποστρέφω"] },
    { g: "τὸ οὖς μέλος ἐστίν· οὐκ ἀρνοῦμαι ὃ ὁ θεὸς φανεροῖ.", e: "The ear is a member; I do not deny what God reveals.", uses: ["οὖς", "μέλος", "ἀρνέομαι", "φανερόω"] },
    { g: "ποῦ καὶ ποίῳ τρόπῳ; πλὴν πιστεύω, διότι ὁ θεὸς λέγει.", e: "Where, and in what kind of way? Yet I believe, because God speaks.", uses: ["ποῦ", "ποῖος", "πλήν", "διότι"] },
  ] },
  { chapter: 4, items: [
    { g: "ἀγοράζει ἀρνίον εἰς θυσίαν τοῦ πάσχα.", e: "He buys a lamb for the Passover sacrifice.", uses: ["ἀγοράζω", "ἀρνίον", "θυσία", "πάσχα"] },
    { g: "ἅπαξ ἐπικαλοῦμαι τὸν σωτῆρα, καὶ ἔχω σωτηρίαν.", e: "Once and for all I call upon the savior, and I have salvation.", uses: ["ἅπαξ", "ἐπικαλέω", "σωτήρ", "σωτηρία"] },
    { g: "ἐλεεῖ ἡμᾶς· τὸ ἔλεος αὐτοῦ παράκλησις τῇ συνειδήσει.", e: "He has mercy on us; his mercy is comfort to the conscience.", uses: ["ἐλεέω", "ἔλεος", "παράκλησις", "συνείδησις"] },
    { g: "Ἰάκωβος καὶ Ἰούδας καὶ Βαρναβᾶς φίλοι εἰσίν.", e: "James and Jude and Barnabas are friends.", uses: ["Ἰάκωβος", "Ἰούδας", "Βαρναβᾶς", "φίλος"] },
    { g: "ὁ τοῦ Καίσαρος δοῦλος μαχαίρᾳ φυλάσσει, καὶ φόβος ἐστίν.", e: "Caesar's servant guards with a sword, and there is fear.", uses: ["Καῖσαρ", "μάχαιρα", "φυλάσσω", "φόβος"] },
    { g: "μισεῖ καὶ ἀδικεῖ καὶ σκανδαλίζει· διὸ ἐπιτιμῶ αὐτῷ.", e: "He hates and does wrong and causes stumbling; so I rebuke him.", uses: ["μισέω", "ἀδικέω", "σκανδαλίζω", "ἐπιτιμάω"] },
    { g: "γαμεῖ τὴν θυγατέρα ἐκ τῆς φυλῆς καὶ δίδωσιν μισθόν.", e: "He marries the daughter from the tribe and gives a payment.", uses: ["γαμέω", "θυγάτηρ", "φυλή", "μισθός"] },
    { g: "ἡ ἐπιθυμία ἐν τῷ σκότει ἁρπάζει· ἀνάγκη ἐστὶν φυγεῖν.", e: "Desire snatches in the darkness; there is a necessity to flee.", uses: ["ἐπιθυμία", "σκότος", "ἁρπάζω", "ἀνάγκη"] },
    { g: "ἡγοῦμαι τὴν γνῶσιν ἀληθινήν, καὶ διακρίνω τὰ πάντα.", e: "I consider the knowledge genuine, and I judge all things.", uses: ["ἡγέομαι", "γνῶσις", "ἀληθινός", "διακρίνω"] },
    { g: "ἴδε, ἃ ποτὲ ἦν παρέρχεται· μιμνῄσκομαι δὲ αὐτῶν.", e: "Behold, what once was passes away; but I remember it.", uses: ["ἴδε", "ποτέ", "παρέρχομαι", "μιμνῄσκομαι"] },
  ] },
  { chapter: 5, items: [
    { g: "ἐν τῷ γάμῳ ὁ νυμφίος γεύεται τὸν οἶνον.", e: "At the wedding the bridegroom tastes the wine.", uses: ["γάμος", "νυμφίος", "γεύομαι", "οἶνος"] },
    { g: "Μαρία καὶ Μαριὰμ φωνοῦσιν· ἥκει ὁ κύριος.", e: "Mary and Mariam call out: the Lord has come.", uses: ["Μαρία", "Μαριάμ", "φωνέω", "ἥκω"] },
    { g: "πόθεν καὶ πόσον; γνωρίζει ὁ θεὸς τὸ μυστήριον.", e: "From where, and how much? God makes the mystery known.", uses: ["πόθεν", "πόσος", "γνωρίζω", "μυστήριον"] },
    { g: "βαστάζει τὸν σταυρόν· ὁ στρατιώτης οὐ νικᾷ αὐτόν.", e: "He bears the cross; the soldier does not overcome him.", uses: ["βαστάζω", "σταυρός", "στρατιώτης", "νικάω"] },
    { g: "ἡ χήρα δέκα ἔτη ἀσθενὴς οὖσα δουλεύει.", e: "The widow, weak for ten years, serves on.", uses: ["χήρα", "δέκα", "ἀσθενής", "δουλεύω"] },
    { g: "ὁ διάκονος καθαρός ἐστιν καὶ ἀληθής, καὶ συνίει.", e: "The servant is clean and honest, and he understands.", uses: ["διάκονος", "καθαρός", "ἀληθής", "συνίημι"] },
    { g: "ἕνεκα τῆς ἀδικίας ἐκχέει δάκρυα καὶ λυπεῖ.", e: "On account of the injustice he pours out tears and grieves.", uses: ["ἕνεκα", "ἀδικία", "ἐκχέω", "λυπέω"] },
    { g: "τὸ δένδρον κεῖται· ἄρτι ἀναβλέπω πρὸς τὸν οὐρανόν.", e: "The tree lies fallen; now I look up toward heaven.", uses: ["δένδρον", "κεῖμαι", "ἄρτι", "ἀναβλέπω"] },
    { g: "Ἰακὼβ καὶ ὁ Ἕλλην προφητεύουσιν πνευματικά.", e: "Jacob and the Greek prophesy spiritual things.", uses: ["Ἰακώβ", "Ἕλλην", "προφητεύω", "πνευματικός"] },
    { g: "τὸ σόν γε ἔργον φρονεῖς καὶ τελεῖς.", e: "Your own work, at least, you ponder and finish.", uses: ["σός", "γέ", "φρονέω", "τελέω"] },
  ] },
  { chapter: 6, items: [
    { g: "ὁ ἁμαρτωλὸς ἄπιστός ἐστιν, ἀλλὰ ἐπιστρέφει καὶ μανθάνει.", e: "The sinner is unbelieving, but he turns back and learns.", uses: ["ἁμαρτωλός", "ἄπιστος", "ἐπιστρέφω", "μανθάνω"] },
    { g: "ἐν τῷ ἀμπελῶνι αὐξάνει ὁ καρπός· ὁ δὲ δοῦλος καταλείπει αὐτόν.", e: "In the vineyard the fruit grows; but the servant leaves it behind.", uses: ["ἀμπελών", "αὐξάνω", "καταλείπω", "παῖς"] },
    { g: "Ἠλίας ἀνάγει τὸν παῖδα καὶ ἰᾶται αὐτόν.", e: "Elijah leads the boy up and heals him.", uses: ["Ἠλίας", "ἀνάγω", "ἰάομαι", "παῖς"] },
    { g: "ἡ ἀσθένεια μεγάλη· ἀσθενεῖ γάρ, καὶ οὐκ ἰσχύει.", e: "The sickness is great, for he is weak and is not strong.", uses: ["ἀσθένεια", "ἀσθενέω", "ἰσχύω", "κρίσις"] },
    { g: "ὁ ἀστὴρ λευκὸς ἐν τῇ νεφέλῃ φαίνεται ἕκαστον μῆνα.", e: "The star shines white in the cloud each month.", uses: ["ἀστήρ", "λευκός", "νεφέλη", "μήν"] },
    { g: "ἡ δέησις καὶ ἡ προσευχὴ πρὸς τὸν θεόν· προσέχομεν οὖν.", e: "The petition and the prayer are toward God; so we pay attention.", uses: ["δέησις", "προσευχή", "προσέχω", "ἐνεργέω"] },
    { g: "ἡ εἰκὼν ἐλευθέρα· μήτε δοῦλος μήποτε αὐτὴν ἀναιρεῖ.", e: "The image is free; and no slave ever destroys it.", uses: ["εἰκών", "ἐλεύθερος", "μήτε", "μήποτε", "ἀναιρέω"] },
    { g: "ἐν τῇ ἑορτῇ πλῆθος πάρεστιν, καὶ ὁ νοῦς πίμπλαται χαρᾶς.", e: "At the festival a multitude is present, and the mind is filled with joy.", uses: ["ἑορτή", "πλῆθος", "πάρειμι", "νοῦς", "πίμπλημι"] },
    { g: "Τιμόθεος τὴν ἐπιστολὴν ἀναγινώσκει περὶ τῆς παρουσίας.", e: "Timothy reads the letter about the coming.", uses: ["Τιμόθεος", "ἐπιστολή", "παρουσία"] },
    { g: "κελεύει καὶ προσκαλεῖται αὐτούς· ὀμνύουσιν δὲ φυγεῖν τὴν πορνείαν.", e: "He orders and summons them; and they swear to flee immorality.", uses: ["κελεύω", "προσκαλέω", "ὀμνύω", "πορνεία"] },
  ] },
];
