// ============================================================
// Greek Vocabulary Database
// ------------------------------------------------------------
// Each set has: id, source, title, and words.
// Each word: g (Greek lexical form), gloss (English), freq (NT
// frequency count from the workbook), tier ('memorize' | 'recognize'),
// icon (a symbol shown with the hint) and mn (the built-in memory hook).
//
// To add new vocabulary: upload workbook photos to Claude and a
// new set object gets appended here. Custom sets added in-app are
// stored in localStorage and merged at runtime.
// ============================================================

const VOCAB_SETS = [
  {
    id: "gd-set-01",
    source: "Going Deeper with New Testament Greek",
    title: "Set 1 — Mark 1 Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀπαγγέλλω", gloss: "I announce, proclaim, report", freq: 45, tier: "memorize", icon: "📢", mn: "ah-pahng-GHEHL-lo ≈ \"a PANG — hard-G HELLO!\" A pang, then you hail everyone: ANNOUNCE." },
      { g: "ἀποδίδωμι", gloss: "I give away, pay, return", freq: 48, tier: "memorize", icon: "💰", mn: "ah-po-THEE-tho-mee ≈ \"APOTHE-tho-me.\" The apothecary hands it back TO ME: PAY UP." },
      { g: "ἄρα", gloss: "so, then, consequently", freq: 49, tier: "memorize", icon: "➡️", mn: "AH-rah ≈ \"AH — RAH!\" The cheer once the point lands: SO, THEN." },
      { g: "ἄφεσις, -εως, ἡ", gloss: "forgiveness", freq: 17, tier: "memorize", icon: "🕊️", mn: "ah-FEH-sees ≈ \"a-FESS-sis.\" Fess up, sis — and it is FORGIVEN." },
      { g: "ἄχρι", gloss: "until (conj. or prep. + gen.)", freq: 49, tier: "memorize", icon: "⏳", mn: "AH-khree ≈ \"a CRY\" (rasped: kh). You cry UNTIL it is over." },
      { g: "βάπτισμα, -ατος, τό", gloss: "baptism", freq: 19, tier: "memorize", icon: "💧", mn: "VAHP-tees-mah ≈ \"VOP-TEASE-ma.\" They whop him under the water: BAPTISM." },
      { g: "δεύτερος", gloss: "second", freq: 43, tier: "memorize", icon: "2️⃣", mn: "THEV-teh-ros ≈ \"THE-VET-ROSE.\" The vet rose in SECOND place." },
      { g: "διακονέω", gloss: "I serve", freq: 37, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEH-o ≈ \"THEE-a-CONE-oh.\" A cone for thee: I SERVE." },
      { g: "διέρχομαι", gloss: "I go through, cross over", freq: 43, tier: "memorize", icon: "🚶", mn: "thee-EHR-kho-meh ≈ \"THE-AIR-I-COMB.\" You comb right THROUGH the air." },
      { g: "ἐκπορεύομαι", gloss: "I go out, come out", freq: 33, tier: "memorize", icon: "🚪", mn: "ehk-po-REV-o-meh ≈ \"ECK-po-REV-o-me.\" Rev it up and GO OUT." },
      { g: "ἐνδύω", gloss: "I clothe myself, put on, wear", freq: 27, tier: "memorize", icon: "👕", mn: "ehn-THEW-o ≈ \"EN-THOU-oh.\" En-thou: you get INTO it — PUT ON your coat." },
      { g: "ἐπιγινώσκω", gloss: "I know, understand, recognize", freq: 44, tier: "memorize", icon: "💡", mn: "eh-pee-ghee-NOS-ko ≈ \"a-PIGGY-KNOWS-ko.\" A piggy KNOWS you: RECOGNIZE." },
      { g: "ἔρημος, ἡ", gloss: "desert, wilderness", freq: 48, tier: "memorize", icon: "🏜️", mn: "EH-ray-mos ≈ \"AIR-RAY-MOSS.\" Air and rays, no moss at all: the DESERT." },
      { g: "ἑτοιμάζω", gloss: "I make ready, prepare", freq: 40, tier: "memorize", icon: "🧰", mn: "heh-TEW-mah-zo ≈ \"he-TWO-ma-zo.\" He gets two for ma: everything READY." },
      { g: "ἔτος, -ους, τό", gloss: "year", freq: 49, tier: "memorize", icon: "📅", mn: "EH-tos ≈ \"a TOSS.\" You toss the old calendar out each YEAR." },
      { g: "εὐδοκέω", gloss: "I am well pleased, approve", freq: 21, tier: "memorize", icon: "😊", mn: "ev-tho-KEH-o ≈ \"EV-THOUGH-KAY-o.\" Ev, though, is okay with it: WELL PLEASED." },
      { g: "Ἠσαΐας, ὁ", gloss: "Isaiah", freq: 22, tier: "memorize", icon: "📜", mn: "ay-sah-EE-ahs ≈ \"a-SAY-EE-as.\" Say it and you have ISAIAH." },
      { g: "θηρίον, τό", gloss: "animal, beast", freq: 46, tier: "memorize", icon: "🦁", mn: "THAY-ree-on ≈ \"THEY'RE-ON.\" They're on me — the wild BEASTS!" },
      { g: "θλῖψις, -εως, ἡ", gloss: "tribulation, affliction, oppression", freq: 45, tier: "memorize", icon: "😰", mn: "THLEEP-sees ≈ \"the-LIPS-SEIZE.\" The lips seize under the pressure: TRIBULATION." },
      { g: "θρίξ, τριχός, ἡ", gloss: "hair", freq: 15, tier: "memorize", icon: "💇", mn: "THREEX ≈ \"THREE-X.\" Three strands of HAIR crossed in an X." },
      { g: "ἱκανός", gloss: "qualified, able", freq: 39, tier: "memorize", icon: "✅", mn: "hee-kah-NOS ≈ \"HE-CAN-nose.\" He can do it — he is ABLE." },
      { g: "Ἰορδάνης, -ου, ὁ", gloss: "the Jordan", freq: 15, tier: "memorize", icon: "🏞️", mn: "ee-or-THAH-nays ≈ \"YOUR-THAW-nays.\" Your thaw feeds the JORDAN." },
      { g: "ἰσχυρός", gloss: "strong, mighty, powerful", freq: 29, tier: "memorize", icon: "💪", mn: "ees-KHEW-ros ≈ \"EASE-CUE-rose.\" On cue he rose — that is STRONG." },
      { g: "καθίζω", gloss: "I cause to sit down, appoint", freq: 46, tier: "memorize", icon: "🪑", mn: "kah-THEE-zo ≈ \"CATHY'S-oh.\" Cathy, oh — SIT DOWN." },
      { g: "κρατέω", gloss: "I grasp, hold (fast), arrest", freq: 47, tier: "memorize", icon: "✊", mn: "krah-TEH-o ≈ \"a-CRATE-oh.\" Grab the crate and HOLD it fast." },
      { g: "μετάνοια, ἡ", gloss: "repentance", freq: 22, tier: "memorize", icon: "🔄", mn: "meh-tah-NEW-ah ≈ \"ME? a-NEW-ah!\" Me, made new — a changed mind: REPENTANCE." },
      { g: "ναός, ὁ", gloss: "temple, sanctuary", freq: 45, tier: "memorize", icon: "🏛️", mn: "nah-OS ≈ \"NOAH'S.\" Noah's holy house: the TEMPLE." },
      { g: "ὅμοιος", gloss: "like, similar", freq: 45, tier: "memorize", icon: "🟰", mn: "ho-MEW-os ≈ \"HOME-EWES.\" Two ewes at home look ALIKE." },
      { g: "ὀπίσω", gloss: "after, behind", freq: 35, tier: "memorize", icon: "👣", mn: "o-PEE-so ≈ \"oh-a-PEA-so.\" The pea rolled off BEHIND you." },
      { g: "οὐαί", gloss: "woe", freq: 46, tier: "memorize", icon: "😱", mn: "oo-EH ≈ \"oo-AY!\" Said aloud it is already a wail: WOE!" },
      { g: "οὐκέτι", gloss: "no longer", freq: 47, tier: "memorize", icon: "🚫", mn: "oo-KEH-tee ≈ \"ooh-KETTLE.\" The kettle is NO LONGER boiling." },
      { g: "πειράζω", gloss: "I tempt, test", freq: 38, tier: "memorize", icon: "🎣", mn: "pee-RAH-zo ≈ \"PEER-RAH-zo.\" He peers at you to TEST you." },
      { g: "ποταμός, ὁ", gloss: "river", freq: 17, tier: "memorize", icon: "🌊", mn: "po-tah-MOS ≈ \"a-POT-o'-MOSS.\" It floats away down the RIVER." },
      { g: "πρό", gloss: "before, in front of, at (+ gen.)", freq: 47, tier: "memorize", icon: "⏪", mn: "PRO ≈ \"a PRO.\" The pro always goes BEFORE the rookie." },
      { g: "προσφέρω", gloss: "I bring to, offer", freq: 47, tier: "memorize", icon: "🎁", mn: "pros-FEH-ro ≈ \"PROS-FERRY-o.\" The pros ferry it over and OFFER it." },
      { g: "Σατανᾶς, -ᾶ, ὁ", gloss: "Satan", freq: 36, tier: "memorize", icon: "😈", mn: "sah-tah-NAHS ≈ \"SATAN-ahs.\" The accuser himself: SATAN." },
      { g: "σταυρόω", gloss: "I crucify", freq: 46, tier: "memorize", icon: "✝️", mn: "STAV-ro-o ≈ \"a STAVE — a ROW — oh.\" A row of wooden staves: they CRUCIFY him." },
      { g: "τεσσεράκοντα", gloss: "forty", freq: 22, tier: "memorize", icon: "4️⃣", mn: "tehs-seh-rah-KON-tah ≈ \"TESS-and-SARAH-COUNT-ah.\" They count to FORTY." },
      { g: "φυλακή, ἡ", gloss: "watch, guard, prison", freq: 47, tier: "memorize", icon: "🔒", mn: "few-lah-KAY ≈ \"a-FEW-lo-KAY.\" A few locked away, Kay: PRISON, a GUARD." },
      { g: "χώρα, ἡ", gloss: "district, region", freq: 28, tier: "memorize", icon: "🗺️", mn: "KHO-rah ≈ \"CORA\" (rasped: kh). Cora owns the whole REGION." },
      // ---- Vocabulary to Recognize ----
      { g: "ἄγριος", gloss: "wild", freq: 3, tier: "recognize", icon: "🌿", mn: "AH-ghree-os ≈ \"ANGRY-os.\" Angry and untamed: WILD." },
      { g: "ἀκρίς, -ίδος, ἡ", gloss: "locust", freq: 4, tier: "recognize", icon: "🦗", mn: "ah-KREES ≈ \"a-CREASE.\" The locusts eat a crease across the field: LOCUST." },
      { g: "βοάω", gloss: "I call, shout, cry out", freq: 12, tier: "recognize", icon: "📣", mn: "vo-AH-o ≈ \"a VOW — AH — OH!\" Every syllable of it is a shout: he CRIES OUT." },
      { g: "δερμάτινος", gloss: "(made of) leather", freq: 2, tier: "recognize", icon: "🧥", mn: "thehr-mah-TEE-nos ≈ \"THERMAL-TEE-nos.\" A thermal tee made of LEATHER." },
      { g: "ἐξομολογέω", gloss: "I confess, admit", freq: 10, tier: "recognize", icon: "🙏", mn: "ehx-o-mo-lo-GHEH-o ≈ \"EGGS-o-mo-lo-GAY-o.\" He logs it all out loud: CONFESS." },
      { g: "εὐθύς", gloss: "straight", freq: 8, tier: "recognize", icon: "📏", mn: "ev-THEWS ≈ \"EV — THOSE!\" Ev sends those STRAIGHT ahead." },
      { g: "ζώνη, ἡ", gloss: "belt", freq: 8, tier: "recognize", icon: "🎽", mn: "ZO-nay ≈ \"a ZONE-ay.\" The BELT is the zone around your waist." },
      { g: "Ἱεροσολυμίτης, -ου, ὁ", gloss: "inhabitant of Jerusalem", freq: 2, tier: "recognize", icon: "🏙️", mn: "hee-eh-ro-so-lew-MEE-tays ≈ \"HIERO-SO-LEW-mee-tays.\" A JERUSALEM-ite." },
      { g: "ἱμάς, -άντος, ὁ", gloss: "strap, thong", freq: 4, tier: "recognize", icon: "🪢", mn: "hee-MAHS ≈ \"HE-MASHED.\" He mashed the sandal STRAP flat." },
      { g: "κάμηλος, ὁ", gloss: "camel", freq: 6, tier: "recognize", icon: "🐪", mn: "kah-MAY-los ≈ \"ka-MAY-los.\" Say it and it is already the CAMEL." },
      { g: "κατασκευάζω", gloss: "I make ready, prepare", freq: 11, tier: "recognize", icon: "🔨", mn: "kah-tah-SKEV-ah-zo ≈ \"CUT-a-SKEV-a-zo.\" Cut it, skewer it, PREPARE the feast." },
      { g: "κύπτω", gloss: "I bend down", freq: 2, tier: "recognize", icon: "🙇", mn: "KEWP-to ≈ \"CUTE-P-toe\" — like \"cute\" with a P. He stoops low: BEND DOWN." },
      { g: "μέλι, -ιτος, τό", gloss: "honey", freq: 4, tier: "recognize", icon: "🍯", mn: "MEH-lee ≈ \"MEL-ee.\" Mel loves his HONEY." },
      { g: "Ναζαρέτ, ἡ", gloss: "Nazareth", freq: 12, tier: "recognize", icon: "🏘️", mn: "nah-zah-REHT ≈ \"NAZA-RET.\" The town itself: NAZARETH." },
      { g: "ὀσφῦς, ἡ", gloss: "waist", freq: 8, tier: "recognize", icon: "🧍", mn: "os-FEWS ≈ \"OS-FEWS.\" The few bones at your WAIST." },
      { g: "περιστερά, ἡ", gloss: "dove, pigeon", freq: 10, tier: "recognize", icon: "🕊️", mn: "peh-ree-steh-RAH ≈ \"PERRY'S-STAIR-ah.\" A DOVE settles on Perry's stair." },
      { g: "σχίζω", gloss: "I split, divide, separate, tear apart", freq: 11, tier: "recognize", icon: "✂️", mn: "SKHEE-zo ≈ \"SKIS-oh.\" The skis SPLIT the snow apart." },
      { g: "τρίβος, ἡ", gloss: "path", freq: 3, tier: "recognize", icon: "🛤️", mn: "TREE-vos ≈ \"TREE-VOSS.\" The PATH worn between the trees." },
      { g: "ὑπόδημα, -ατος, τό", gloss: "sandal", freq: 10, tier: "recognize", icon: "👡", mn: "hew-po-THAY-mah ≈ \"HEW-po-THAY-ma.\" Who put THEM on? The SANDALS." }
    ]
  },
  {
    id: "gd-set-02",
    source: "Going Deeper with New Testament Greek",
    title: "Set 2 — Romans Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀγρός, ὁ", gloss: "field, country", freq: 36, tier: "memorize", icon: "🌾", mn: "ah-GHROS ≈ \"a GROSS.\" A gross of wheat standing in the FIELD." },
      { g: "ἀκάθαρτος", gloss: "unclean, impure", freq: 32, tier: "memorize", icon: "🚱", mn: "ah-kah-THAHR-tos ≈ \"a-CATHARTIC-os.\" A cathartic cleanses — and the ἀ- cancels it: UNCLEAN." },
      { g: "ἀκροβυστία, ἡ", gloss: "uncircumcision", freq: 20, tier: "memorize", icon: "✂️", mn: "ah-kro-VEW-stee-ah ≈ \"ACRO-VIEWS-tee-ah.\" ἄκρον is the tip, left as it was: UNCIRCUMCISION." },
      { g: "ἀναγινώσκω", gloss: "I read (aloud)", freq: 32, tier: "memorize", icon: "📖", mn: "ah-nah-ghee-NOS-ko ≈ \"ANNA-GHEE-KNOWS-ko.\" Anna knows her letters — she READS it aloud." },
      { g: "ἄνεμος, ὁ", gloss: "wind", freq: 31, tier: "memorize", icon: "🌬️", mn: "AH-neh-mos ≈ \"an-ANEM-ometer.\" An anemometer measures the WIND." },
      { g: "ἀρνέομαι", gloss: "I deny, reject", freq: 33, tier: "memorize", icon: "🙅", mn: "ahr-NEH-o-meh ≈ \"ARE? NAY! — o-me.\" Asked, and he says nay: I DENY it." },
      { g: "βιβλίον, τό", gloss: "book, scroll", freq: 34, tier: "memorize", icon: "📕", mn: "veev-LEE-on ≈ \"VEEV-lee-on.\" Our word BIBLE, softened: the BOOK, the scroll." },
      { g: "διαθήκη, ἡ", gloss: "covenant, decree, last will and testament", freq: 33, tier: "memorize", icon: "📜", mn: "thee-ah-THAY-kay ≈ \"THEE-a-THEY-kay.\" Thee and they, bound by terms: COVENANT, a last will." },
      { g: "διακονία, ἡ", gloss: "service, office, ministry, deacon", freq: 34, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEE-ah ≈ \"THEE-a-CONE-ee-ah.\" The DEACON serves thee a cone: MINISTRY." },
      { g: "δικαιόω", gloss: "I justify, vindicate", freq: 39, tier: "memorize", icon: "⚖️", mn: "thee-KEH-o-o ≈ \"THEE? OKAY-o!\" Declared in the right: JUSTIFY." },
      { g: "διότι", gloss: "for, because, therefore", freq: 23, tier: "memorize", icon: "➡️", mn: "thee-O-tee ≈ \"THEE-oh-TEA.\" Why? BECAUSE thee wanted tea." },
      { g: "δυνατός", gloss: "powerful, strong, mighty, able", freq: 32, tier: "memorize", icon: "💪", mn: "thew-nah-TOS ≈ \"THEWS-a-TOSS.\" Thews are sinews — strong enough to toss it: POWERFUL." },
      { g: "ἐγγύς", gloss: "near, close to", freq: 31, tier: "memorize", icon: "📍", mn: "ehng-GHEWS ≈ \"ANGUISH.\" So close it presses on you: NEAR." },
      { g: "ἔξεστιν", gloss: "it is lawful, permitted", freq: 31, tier: "memorize", icon: "✅", mn: "ehx-eh-STEEN ≈ \"the EXIT'S-TEEN.\" That exit is allowed: IT IS LAWFUL." },
      { g: "ἐπίγνωσις, -εως, ἡ", gloss: "knowledge, recognition", freq: 20, tier: "memorize", icon: "💡", mn: "eh-pee-ghno-SEES ≈ \"a-PIGGY-KNOWS-ees.\" What the piggy knows in full: KNOWLEDGE." },
      { g: "εὐθέως", gloss: "immediately", freq: 36, tier: "memorize", icon: "⚡", mn: "ev-THEH-os ≈ \"EV — THOSE!\" Ev wants those right now: IMMEDIATELY." },
      { g: "ἐχθρός", gloss: "hostile, hated", freq: 32, tier: "memorize", icon: "⚔️", mn: "ehkh-THROS ≈ \"EXTRA-GROSS.\" Extra gross to you: HOSTILE, hated." },
      { g: "ἥλιος, ὁ", gloss: "sun", freq: 32, tier: "memorize", icon: "☀️", mn: "HAY-lee-os ≈ \"HELIOS / HELIUM.\" Helium was found in the SUN." },
      { g: "ἱερεύς, -έως, ὁ", gloss: "priest", freq: 31, tier: "memorize", icon: "🕍", mn: "hee-eh-REVS ≈ \"HIERO-REVS.\" The HIERarch of the temple: the PRIEST." },
      { g: "καθαρίζω", gloss: "I cleanse, purify", freq: 31, tier: "memorize", icon: "🧼", mn: "kah-thah-REE-zo ≈ \"CATHARSIS-o.\" Catharsis is a washing out: I CLEANSE." },
      { g: "καταργέω", gloss: "I cancel, nullify, make void", freq: 27, tier: "memorize", icon: "🚫", mn: "kah-tahr-GHEH-o ≈ \"CUT-the-ARGUE-o.\" Cut the argument dead: NULLIFY, make void." },
      { g: "λογίζομαι", gloss: "I account, reckon, conclude", freq: 40, tier: "memorize", icon: "🧮", mn: "lo-GHEE-zo-meh ≈ \"LOGIC-zo-me.\" I run the logic: I RECKON, I account." },
      { g: "μέλος, -ους, τό", gloss: "member, part, limb", freq: 34, tier: "memorize", icon: "🦵", mn: "MEH-los ≈ \"MELOS / MELODY.\" A melody has parts, a body has LIMBS: MEMBER." },
      { g: "ναί", gloss: "yes, certainly, indeed", freq: 33, tier: "memorize", icon: "👍", mn: "NEH ≈ \"NEH.\" Careful — it sounds like our \"nay\" but means the opposite: YES." },
      { g: "νυνί", gloss: "now", freq: 20, tier: "memorize", icon: "⏱️", mn: "new-NEE ≈ \"NEW-nee.\" What is new is what is NOW." },
      { g: "ὀργή, ἡ", gloss: "anger, wrath, punishment", freq: 36, tier: "memorize", icon: "😤", mn: "or-GHAY ≈ \"an OAR — GAY?\" No: he swings the oar in fury. ANGER, WRATH." },
      { g: "οὖς, ὠτός, τό", gloss: "ear, hearing", freq: 36, tier: "memorize", icon: "👂", mn: "OOS ≈ \"OOZE.\" Cup it and listen — the EAR." },
      { g: "παραγίνομαι", gloss: "I come, arrive, appear", freq: 37, tier: "memorize", icon: "🛬", mn: "pah-rah-ghee-NO-meh ≈ \"PARA-GUY-no-me.\" The parachute guy lands: I ARRIVE." },
      { g: "παρρησία, ἡ", gloss: "confidence, boldness", freq: 31, tier: "memorize", icon: "🗣️", mn: "pahr-ray-SEE-ah ≈ \"PA-RAISES-ya.\" Pa raises you up to speak: BOLDNESS, confidence." },
      { g: "περιτομή, ἡ", gloss: "circumcision", freq: 36, tier: "memorize", icon: "✂️", mn: "peh-ree-to-MAY ≈ \"PERI-TOMY.\" Peri- is around, -tomy is a cut: CIRCUMCISION." },
      { g: "πλήν", gloss: "yet, however, but", freq: 31, tier: "memorize", icon: "↩️", mn: "PLAYN ≈ \"PLAIN.\" Plain and simple — YET, however." },
      { g: "ποῖος", gloss: "of what kind?", freq: 33, tier: "memorize", icon: "❓", mn: "PEW-os ≈ \"PEW-os.\" What kind of pew is that? OF WHAT KIND?" },
      { g: "ποτήριον, τό", gloss: "cup", freq: 31, tier: "memorize", icon: "🍷", mn: "po-TAY-ree-on ≈ \"POTTERY-on.\" Pottery is what the CUP is made of." },
      { g: "ποῦ", gloss: "where?", freq: 48, tier: "memorize", icon: "🧭", mn: "POO ≈ \"POO.\" WHERE did that come from?" },
      { g: "πτωχός", gloss: "poor", freq: 34, tier: "memorize", icon: "🪙", mn: "pto-KHOS ≈ \"p-TOE-KOSS.\" So poor his toes are through the socks: POOR." },
      { g: "ὑποστρέφω", gloss: "I turn back, return", freq: 35, tier: "memorize", icon: "🔙", mn: "hew-po-STREH-fo ≈ \"HUE-po-STROPHE-o.\" A strophe is a turn — turn back: RETURN." },
      { g: "ὑστερέω", gloss: "I fall short of, lack", freq: 16, tier: "memorize", icon: "📉", mn: "hew-steh-REH-o ≈ \"HYSTER-eh-o.\" Hysteros is later — he came in last: I FALL SHORT." },
      { g: "φανερόω", gloss: "I reveal, make manifest, show", freq: 49, tier: "memorize", icon: "🔦", mn: "fah-neh-RO-o ≈ \"FAN-a-ROW-o.\" The fan blows the cover off the row: I REVEAL." },
      { g: "Φίλιππος, ὁ", gloss: "Philip", freq: 36, tier: "memorize", icon: "🧑", mn: "FEE-leep-pos ≈ \"PHILIP with an F.\" Philip." },
      { g: "χωρίς", gloss: "without, apart from", freq: 41, tier: "memorize", icon: "➗", mn: "kho-REES ≈ \"CHORES.\" He did the chores WITHOUT any help: apart from." },
      // ---- Vocabulary to Recognize (no built-in hook: these are pass-through) ----
      { g: "ἁμάρτημα, -ατος, τό", gloss: "sin, transgression", freq: 4, tier: "recognize" },
      { g: "ἀνοχή, ἡ", gloss: "forbearance, tolerance", freq: 2, tier: "recognize" },
      { g: "ἀπολύτρωσις, -εως, ἡ", gloss: "redemption, release, deliverance", freq: 10, tier: "recognize" },
      { g: "διαστολή, ἡ", gloss: "distinction, difference", freq: 3, tier: "recognize" },
      { g: "δωρεάν", gloss: "freely, as a gift, without payment", freq: 9, tier: "recognize" },
      { g: "εἴπερ", gloss: "if indeed, if perhaps", freq: 6, tier: "recognize" },
      { g: "ἐκκλείω", gloss: "I exclude, shut out", freq: 2, tier: "recognize" },
      { g: "ἔνδειξις, ἡ", gloss: "demonstration, proof", freq: 4, tier: "recognize" },
      { g: "ἱλαστήριον, τό", gloss: "propitiation", freq: 2, tier: "recognize" },
      { g: "καύχησις, ἡ", gloss: "boasting", freq: 11, tier: "recognize" },
      { g: "πάρεσις, ἡ", gloss: "passing over", freq: 1, tier: "recognize" },
      { g: "προγίνομαι", gloss: "it happens before, be done before", freq: 1, tier: "recognize" },
      { g: "προτίθημι", gloss: "I present, put forward, display publicly", freq: 3, tier: "recognize" },
      { g: "ὑπόδικος", gloss: "answerable, accountable", freq: 1, tier: "recognize" },
      { g: "φράσσω", gloss: "I shut, close", freq: 3, tier: "recognize" }
    ]
  }
];
