// ============================================================
// Greek Vocabulary Database
// ------------------------------------------------------------
// Each set has: id, source, chapter, title, and words. The chapter is
// the workbook chapter the page came from; it drives the chapter picker,
// and can be reassigned in Settings without editing this file.
// Each word: g (Greek lexical form), gloss (English), freq (NT
// frequency count from the workbook), tier ('memorize' | 'recognize'),
// icon (a symbol shown with the hint) and mn (the built-in memory hook).
//
// To add new vocabulary: upload workbook photos to Claude and a
// new set object gets appended here. Custom sets added in-app are
// stored in localStorage and merged at runtime.
// ============================================================

const VOCAB_SETS = [
  {
    id: "gd-set-01",
    source: "Going Deeper with New Testament Greek",
    chapter: 2,
    title: "Chapter 2 — Mark 1 Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀπαγγέλλω", gloss: "I announce, proclaim, report", freq: 45, tier: "memorize", icon: "📢", mn: "ah-pahng-GHEHL-lo ≈ \"a PANG — hard-G HELLO!\" A pang, then you hail everyone: ANNOUNCE." },
      { g: "ἀποδίδωμι", gloss: "I give away, pay, return", freq: 48, tier: "memorize", icon: "💰", mn: "ah-po-THEE-tho-mee ≈ \"APOTHE-tho-me.\" ἀπό (back) + δίδωμι (give): PAY IT BACK." },
      { g: "ἄρα", gloss: "so, then, consequently", freq: 49, tier: "memorize", icon: "➡️", mn: "AH-rah ≈ \"AH — RAH!\" The cheer once the point lands: SO, THEN." },
      { g: "ἄφεσις, -εως, ἡ", gloss: "forgiveness", freq: 17, tier: "memorize", icon: "🕊️", mn: "ah-FEH-sees ≈ \"a-FESS-sis.\" Fess up, sis — and it is FORGIVEN." },
      { g: "ἄχρι", gloss: "until (conj. or prep. + gen.)", freq: 49, tier: "memorize", icon: "⏳", mn: "AH-khree ≈ \"a CRY\" (rasped: kh). You cry UNTIL it is over." },
      { g: "βάπτισμα, -ατος, τό", gloss: "baptism", freq: 19, tier: "memorize", icon: "💧", mn: "VAHP-tees-mah ≈ \"VOP-TEASE-ma.\" Spelled βαπτ-, our BAPTISM — Koine β says \"v\"." },
      { g: "δεύτερος", gloss: "second", freq: 43, tier: "memorize", icon: "2️⃣", mn: "THEV-teh-ros ≈ \"THE-VET-ROSE.\" Spelled δευτ-, our DEUTERONOMY: the SECOND law." },
      { g: "διακονέω", gloss: "I serve", freq: 37, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEH-o ≈ \"THEE-a-CONE-oh.\" Spelled δ, our DEACON — but Koine δ says \"th\": I SERVE." },
      { g: "διέρχομαι", gloss: "I go through, cross over", freq: 43, tier: "memorize", icon: "🚶", mn: "thee-EHR-kho-meh ≈ \"THE-AIR-I-COMB.\" You comb right THROUGH the air." },
      { g: "ἐκπορεύομαι", gloss: "I go out, come out", freq: 33, tier: "memorize", icon: "🚪", mn: "ehk-po-REV-o-meh ≈ \"ECK-po-REV-o-me.\" Rev it up and GO OUT." },
      { g: "ἐνδύω", gloss: "I clothe myself, put on, wear", freq: 27, tier: "memorize", icon: "👕", mn: "ehn-THEW-o ≈ \"EN-THOU-oh.\" En-thou: you get INTO it — PUT ON your coat." },
      { g: "ἐπιγινώσκω", gloss: "I know, understand, recognize", freq: 44, tier: "memorize", icon: "💡", mn: "eh-pee-ghee-NOS-ko ≈ \"a-PIGGY-KNOWS-ko.\" A piggy KNOWS you: RECOGNIZE." },
      { g: "ἔρημος, ἡ", gloss: "desert, wilderness", freq: 48, tier: "memorize", icon: "🏜️", mn: "EH-ray-mos ≈ \"AIR-RAY-MOSS.\" Air and rays, no moss at all: the DESERT." },
      { g: "ἑτοιμάζω", gloss: "I make ready, prepare", freq: 40, tier: "memorize", icon: "🧰", mn: "heh-TEW-mah-zo ≈ \"he-TWO-ma-zo.\" He gets two for ma: everything READY." },
      { g: "ἔτος, -ους, τό", gloss: "year", freq: 49, tier: "memorize", icon: "📅", mn: "EH-tos ≈ \"a TOSS.\" You toss the old calendar out each YEAR." },
      { g: "εὐδοκέω", gloss: "I am well pleased, approve", freq: 21, tier: "memorize", icon: "😊", mn: "ev-tho-KEH-o ≈ \"EV-THOUGH-KAY-o.\" Ev, though, is okay with it: WELL PLEASED." },
      { g: "Ἠσαΐας, ὁ", gloss: "Isaiah", freq: 22, tier: "memorize", icon: "📜", mn: "ay-sah-EE-ahs ≈ \"a-SAY-EE-as.\" Say it and you have ISAIAH." },
      { g: "θηρίον, τό", gloss: "animal, beast", freq: 46, tier: "memorize", icon: "🦁", mn: "THAY-ree-on ≈ \"THEY'RE-ON.\" They're on me — the wild BEASTS!" },
      { g: "θλῖψις, -εως, ἡ", gloss: "tribulation, affliction, oppression", freq: 45, tier: "memorize", icon: "😰", mn: "THLEEP-sees ≈ \"the-LIPS-SEIZE.\" The lips seize under the pressure: TRIBULATION." },
      { g: "θρίξ, τριχός, ἡ", gloss: "hair", freq: 15, tier: "memorize", icon: "💇", mn: "THREEX ≈ \"THREE-X.\" Three strands of HAIR crossed in an X." },
      { g: "ἱκανός", gloss: "qualified, able", freq: 39, tier: "memorize", icon: "✅", mn: "hee-kah-NOS ≈ \"HE-CAN-nose.\" He can do it — he is ABLE." },
      { g: "Ἰορδάνης, -ου, ὁ", gloss: "the Jordan", freq: 15, tier: "memorize", icon: "🏞️", mn: "ee-or-THAH-nays ≈ \"YOUR-THAW-nays.\" Spelled Ἰορδ-, the JORDAN, its δ sounding \"th\"." },
      { g: "ἰσχυρός", gloss: "strong, mighty, powerful", freq: 29, tier: "memorize", icon: "💪", mn: "ees-KHEW-ros ≈ \"EASE-CUE-rose.\" On cue he rose — that is STRONG." },
      { g: "καθίζω", gloss: "I cause to sit down, appoint", freq: 46, tier: "memorize", icon: "🪑", mn: "kah-THEE-zo ≈ \"CATHY'S-oh.\" Cathy, oh — SIT DOWN." },
      { g: "κρατέω", gloss: "I grasp, hold (fast), arrest", freq: 47, tier: "memorize", icon: "✊", mn: "krah-TEH-o ≈ \"a-CRATE-oh.\" Grab the crate and HOLD it fast." },
      { g: "μετάνοια, ἡ", gloss: "repentance", freq: 22, tier: "memorize", icon: "🔄", mn: "meh-tah-NEW-ah ≈ \"ME? a-NEW-ah!\" Me, made new — a changed mind: REPENTANCE." },
      { g: "ναός, ὁ", gloss: "temple, sanctuary", freq: 45, tier: "memorize", icon: "🏛️", mn: "nah-OS ≈ \"NOAH'S.\" Noah's holy house: the TEMPLE." },
      { g: "ὅμοιος", gloss: "like, similar", freq: 45, tier: "memorize", icon: "🟰", mn: "ho-MEW-os ≈ \"HOME-EWES.\" Two ewes at home look ALIKE." },
      { g: "ὀπίσω", gloss: "after, behind", freq: 35, tier: "memorize", icon: "👣", mn: "o-PEE-so ≈ \"oh-a-PEA-so.\" The pea rolled off BEHIND you." },
      { g: "οὐαί", gloss: "woe", freq: 46, tier: "memorize", icon: "😱", mn: "oo-EH ≈ \"oo-AY!\" Said aloud it is already a wail: WOE!" },
      { g: "οὐκέτι", gloss: "no longer", freq: 47, tier: "memorize", icon: "🚫", mn: "oo-KEH-tee ≈ \"ooh-KETTLE.\" The kettle is NO LONGER boiling." },
      { g: "πειράζω", gloss: "I tempt, test", freq: 38, tier: "memorize", icon: "🎣", mn: "pee-RAH-zo ≈ \"PEER-RAH-zo.\" He peers at you to TEST you." },
      { g: "ποταμός, ὁ", gloss: "river", freq: 17, tier: "memorize", icon: "🌊", mn: "po-tah-MOS ≈ \"a-POT-o'-MOSS.\" It floats away down the RIVER." },
      { g: "πρό", gloss: "before, in front of, at (+ gen.)", freq: 47, tier: "memorize", icon: "⏪", mn: "PRO ≈ \"a PRO.\" The pro always goes BEFORE the rookie." },
      { g: "προσφέρω", gloss: "I bring to, offer", freq: 47, tier: "memorize", icon: "🎁", mn: "pros-FEH-ro ≈ \"PROS-FERRY-o.\" The pros ferry it over and OFFER it." },
      { g: "Σατανᾶς, -ᾶ, ὁ", gloss: "Satan", freq: 36, tier: "memorize", icon: "😈", mn: "sah-tah-NAHS ≈ \"SATAN-ahs.\" The accuser himself: SATAN." },
      { g: "σταυρόω", gloss: "I crucify", freq: 46, tier: "memorize", icon: "✝️", mn: "STAV-ro-o ≈ \"a STAVE — a ROW — oh.\" A row of wooden staves: they CRUCIFY him." },
      { g: "τεσσεράκοντα", gloss: "forty", freq: 22, tier: "memorize", icon: "4️⃣", mn: "tehs-seh-rah-KON-tah ≈ \"TESS-and-SARAH-COUNT-ah.\" They count to FORTY." },
      { g: "φυλακή, ἡ", gloss: "watch, guard, prison", freq: 47, tier: "memorize", icon: "🔒", mn: "few-lah-KAY ≈ \"a-FEW-lo-KAY.\" A few locked away, Kay: PRISON, a GUARD." },
      { g: "χώρα, ἡ", gloss: "district, region", freq: 28, tier: "memorize", icon: "🗺️", mn: "KHO-rah ≈ \"CORA\" (rasped: kh). Cora owns the whole REGION." },
      // ---- Vocabulary to Recognize ----
      { g: "ἄγριος", gloss: "wild", freq: 3, tier: "recognize", icon: "🌿", mn: "AH-ghree-os ≈ \"ANGRY-os.\" Angry and untamed: WILD." },
      { g: "ἀκρίς, -ίδος, ἡ", gloss: "locust", freq: 4, tier: "recognize", icon: "🦗", mn: "ah-KREES ≈ \"a-CREASE.\" The locusts eat a crease across the field: LOCUST." },
      { g: "βοάω", gloss: "I call, shout, cry out", freq: 12, tier: "recognize", icon: "📣", mn: "vo-AH-o ≈ \"a VOW — AH — OH!\" Every syllable of it is a shout: he CRIES OUT." },
      { g: "δερμάτινος", gloss: "(made of) leather", freq: 2, tier: "recognize", icon: "🧥", mn: "thehr-mah-TEE-nos ≈ \"THERMAL-TEE-nos.\" Spelled δερμ-, our DERMATOLOGY — skin, so (made of) LEATHER." },
      { g: "ἐξομολογέω", gloss: "I confess, admit", freq: 10, tier: "recognize", icon: "🙏", mn: "ehx-o-mo-lo-GHEH-o ≈ \"EGGS-o-mo-lo-GAY-o.\" He logs it all out loud: CONFESS." },
      { g: "εὐθύς", gloss: "straight", freq: 8, tier: "recognize", icon: "📏", mn: "ev-THEWS ≈ \"EV — THOSE!\" Ev sends those STRAIGHT ahead." },
      { g: "ζώνη, ἡ", gloss: "belt", freq: 8, tier: "recognize", icon: "🎽", mn: "ZO-nay ≈ \"a ZONE-ay.\" The BELT is the zone around your waist." },
      { g: "Ἱεροσολυμίτης, -ου, ὁ", gloss: "inhabitant of Jerusalem", freq: 2, tier: "recognize", icon: "🏙️", mn: "hee-eh-ro-so-lew-MEE-tays ≈ \"HIERO-SO-LEW-mee-tays.\" A JERUSALEM-ite." },
      { g: "ἱμάς, -άντος, ὁ", gloss: "strap, thong", freq: 4, tier: "recognize", icon: "🪢", mn: "hee-MAHS ≈ \"HE-MASHED.\" He mashed the sandal STRAP flat." },
      { g: "κάμηλος, ὁ", gloss: "camel", freq: 6, tier: "recognize", icon: "🐪", mn: "kah-MAY-los ≈ \"ka-MAY-los.\" Say it and it is already the CAMEL." },
      { g: "κατασκευάζω", gloss: "I make ready, prepare", freq: 11, tier: "recognize", icon: "🔨", mn: "kah-tah-SKEV-ah-zo ≈ \"CUT-a-SKEV-a-zo.\" Cut it, skewer it, PREPARE the feast." },
      { g: "κύπτω", gloss: "I bend down", freq: 2, tier: "recognize", icon: "🙇", mn: "KEWP-to ≈ \"CUTE-P-toe\" — like \"cute\" with a P. He stoops low: BEND DOWN." },
      { g: "μέλι, -ιτος, τό", gloss: "honey", freq: 4, tier: "recognize", icon: "🍯", mn: "MEH-lee ≈ \"MEL-ee.\" Mel loves his HONEY." },
      { g: "Ναζαρέτ, ἡ", gloss: "Nazareth", freq: 12, tier: "recognize", icon: "🏘️", mn: "nah-zah-REHT ≈ \"NAZA-RET.\" The town itself: NAZARETH." },
      { g: "ὀσφῦς, ἡ", gloss: "waist", freq: 8, tier: "recognize", icon: "🧍", mn: "os-FEWS ≈ \"OS-FEWS.\" The few bones at your WAIST." },
      { g: "περιστερά, ἡ", gloss: "dove, pigeon", freq: 10, tier: "recognize", icon: "🕊️", mn: "peh-ree-steh-RAH ≈ \"PERRY'S-STAIR-ah.\" A DOVE settles on Perry's stair." },
      { g: "σχίζω", gloss: "I split, divide, separate, tear apart", freq: 11, tier: "recognize", icon: "✂️", mn: "SKHEE-zo ≈ \"SKIS-oh.\" The skis SPLIT the snow apart." },
      { g: "τρίβος, ἡ", gloss: "path", freq: 3, tier: "recognize", icon: "🛤️", mn: "TREE-vos ≈ \"TREE-VOSS.\" The PATH worn between the trees." },
      { g: "ὑπόδημα, -ατος, τό", gloss: "sandal", freq: 10, tier: "recognize", icon: "👡", mn: "hew-po-THAY-mah ≈ \"HEW-po-THAY-ma.\" ὑπό (under) + δέω (bind) — bound under the foot: SANDAL." }
    ]
  },
  {
    id: "gd-set-02",
    source: "Going Deeper with New Testament Greek",
    chapter: 3,
    title: "Chapter 3 — Romans Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀγρός, ὁ", gloss: "field, country", freq: 36, tier: "memorize", icon: "🌾", mn: "ah-GHROS ≈ \"a GROSS.\" A gross of wheat standing in the FIELD." },
      { g: "ἀκάθαρτος", gloss: "unclean, impure", freq: 32, tier: "memorize", icon: "🚱", mn: "ah-kah-THAHR-tos ≈ \"a-CATHARTIC-os.\" A cathartic cleanses — and the ἀ- cancels it: UNCLEAN." },
      { g: "ἀκροβυστία, ἡ", gloss: "uncircumcision", freq: 20, tier: "memorize", icon: "✂️", mn: "ah-kro-VEW-stee-ah ≈ \"ACRO-VIEWS-tee-ah.\" ἄκρον is the tip, left as it was: UNCIRCUMCISION." },
      { g: "ἀναγινώσκω", gloss: "I read (aloud)", freq: 32, tier: "memorize", icon: "📖", mn: "ah-nah-ghee-NOS-ko ≈ \"ANNA-GHEE-KNOWS-ko.\" Anna knows her letters — she READS it aloud." },
      { g: "ἄνεμος, ὁ", gloss: "wind", freq: 31, tier: "memorize", icon: "🌬️", mn: "AH-neh-mos ≈ \"an-ANEM-ometer.\" An anemometer measures the WIND." },
      { g: "ἀρνέομαι", gloss: "I deny, reject", freq: 33, tier: "memorize", icon: "🙅", mn: "ahr-NEH-o-meh ≈ \"ARE? NAY! — o-me.\" Asked, and he says nay: I DENY it." },
      { g: "βιβλίον, τό", gloss: "book, scroll", freq: 34, tier: "memorize", icon: "📕", mn: "veev-LEE-on ≈ \"VEEV-lee-on.\" Our word BIBLE, softened: the BOOK, the scroll." },
      { g: "διαθήκη, ἡ", gloss: "covenant, decree, last will and testament", freq: 33, tier: "memorize", icon: "📜", mn: "thee-ah-THAY-kay ≈ \"THEE-a-THEY-kay.\" Thee and they, bound by terms: COVENANT, a last will." },
      { g: "διακονία, ἡ", gloss: "service, office, ministry, deacon", freq: 34, tier: "memorize", icon: "🍽️", mn: "thee-ah-ko-NEE-ah ≈ \"THEE-a-CONE-ee-ah.\" The root of DEACON, its δ softened to \"th\": MINISTRY." },
      { g: "δικαιόω", gloss: "I justify, vindicate", freq: 39, tier: "memorize", icon: "⚖️", mn: "thee-KEH-o-o ≈ \"THEE? OKAY-o!\" From δίκαιος, righteous: declared in the right, JUSTIFY." },
      { g: "διότι", gloss: "for, because, therefore", freq: 23, tier: "memorize", icon: "➡️", mn: "thee-O-tee ≈ \"THEE-oh-TEA.\" Why? BECAUSE thee wanted tea." },
      { g: "δυνατός", gloss: "powerful, strong, mighty, able", freq: 32, tier: "memorize", icon: "💪", mn: "thew-nah-TOS ≈ \"THEWS-a-TOSS.\" Spelled δυν-, our DYNAMITE: POWERFUL, able." },
      { g: "ἐγγύς", gloss: "near, close to", freq: 31, tier: "memorize", icon: "📍", mn: "ehng-GHEWS ≈ \"ANGUISH.\" So close it presses on you: NEAR." },
      { g: "ἔξεστιν", gloss: "it is lawful, permitted", freq: 31, tier: "memorize", icon: "✅", mn: "ehx-eh-STEEN ≈ \"the EXIT'S-TEEN.\" That exit is allowed: IT IS LAWFUL." },
      { g: "ἐπίγνωσις, -εως, ἡ", gloss: "knowledge, recognition", freq: 20, tier: "memorize", icon: "💡", mn: "eh-pee-ghno-SEES ≈ \"a-PIGGY-KNOWS-ees.\" What the piggy knows in full: KNOWLEDGE." },
      { g: "εὐθέως", gloss: "immediately", freq: 36, tier: "memorize", icon: "⚡", mn: "ev-THEH-os ≈ \"EV — THOSE!\" Ev wants those right now: IMMEDIATELY." },
      { g: "ἐχθρός", gloss: "hostile, hated", freq: 32, tier: "memorize", icon: "⚔️", mn: "ehkh-THROS ≈ \"EXTRA-GROSS.\" Extra gross to you: HOSTILE, hated." },
      { g: "ἥλιος, ὁ", gloss: "sun", freq: 32, tier: "memorize", icon: "☀️", mn: "HAY-lee-os ≈ \"HELIOS / HELIUM.\" Helium was found in the SUN." },
      { g: "ἱερεύς, -έως, ὁ", gloss: "priest", freq: 31, tier: "memorize", icon: "🕍", mn: "hee-eh-REVS ≈ \"HIERO-REVS.\" The HIERarch of the temple: the PRIEST." },
      { g: "καθαρίζω", gloss: "I cleanse, purify", freq: 31, tier: "memorize", icon: "🧼", mn: "kah-thah-REE-zo ≈ \"CATHARSIS-o.\" Catharsis is a washing out: I CLEANSE." },
      { g: "καταργέω", gloss: "I cancel, nullify, make void", freq: 27, tier: "memorize", icon: "🚫", mn: "kah-tahr-GHEH-o ≈ \"CUT-the-ARGUE-o.\" Cut the argument dead: NULLIFY, make void." },
      { g: "λογίζομαι", gloss: "I account, reckon, conclude", freq: 40, tier: "memorize", icon: "🧮", mn: "lo-GHEE-zo-meh ≈ \"LOGIC-zo-me.\" I run the logic: I RECKON, I account." },
      { g: "μέλος, -ους, τό", gloss: "member, part, limb", freq: 34, tier: "memorize", icon: "🦵", mn: "MEH-los ≈ \"MELOS / MELODY.\" A melody has parts, a body has LIMBS: MEMBER." },
      { g: "ναί", gloss: "yes, certainly, indeed", freq: 33, tier: "memorize", icon: "👍", mn: "NEH ≈ \"NEH.\" Careful — it sounds like our \"nay\" but means the opposite: YES." },
      { g: "νυνί", gloss: "now", freq: 20, tier: "memorize", icon: "⏱️", mn: "new-NEE ≈ \"NEW-nee.\" What is new is what is NOW." },
      { g: "ὀργή, ἡ", gloss: "anger, wrath, punishment", freq: 36, tier: "memorize", icon: "😤", mn: "or-GHAY ≈ \"an OAR — GAY?\" No: he swings the oar in fury. ANGER, WRATH." },
      { g: "οὖς, ὠτός, τό", gloss: "ear, hearing", freq: 36, tier: "memorize", icon: "👂", mn: "OOS ≈ \"OOZE.\" Cup it and listen — the EAR." },
      { g: "παραγίνομαι", gloss: "I come, arrive, appear", freq: 37, tier: "memorize", icon: "🛬", mn: "pah-rah-ghee-NO-meh ≈ \"PARA-GUY-no-me.\" The parachute guy lands: I ARRIVE." },
      { g: "παρρησία, ἡ", gloss: "confidence, boldness", freq: 31, tier: "memorize", icon: "🗣️", mn: "pahr-ray-SEE-ah ≈ \"PA-RAISES-ya.\" Pa raises you up to speak: BOLDNESS, confidence." },
      { g: "περιτομή, ἡ", gloss: "circumcision", freq: 36, tier: "memorize", icon: "✂️", mn: "peh-ree-to-MAY ≈ \"PERI-TOMY.\" Peri- is around, -tomy is a cut: CIRCUMCISION." },
      { g: "πλήν", gloss: "yet, however, but", freq: 31, tier: "memorize", icon: "↩️", mn: "PLAYN ≈ \"PLAIN.\" Plain and simple — YET, however." },
      { g: "ποῖος", gloss: "of what kind?", freq: 33, tier: "memorize", icon: "❓", mn: "PEW-os ≈ \"PEW-os.\" What kind of pew is that? OF WHAT KIND?" },
      { g: "ποτήριον, τό", gloss: "cup", freq: 31, tier: "memorize", icon: "🍷", mn: "po-TAY-ree-on ≈ \"POTTERY-on.\" Pottery is what the CUP is made of." },
      { g: "ποῦ", gloss: "where?", freq: 48, tier: "memorize", icon: "🧭", mn: "POO ≈ \"POO.\" WHERE did that come from?" },
      { g: "πτωχός", gloss: "poor", freq: 34, tier: "memorize", icon: "🪙", mn: "pto-KHOS ≈ \"p-TOE-KOSS.\" So poor his toes are through the socks: POOR." },
      { g: "ὑποστρέφω", gloss: "I turn back, return", freq: 35, tier: "memorize", icon: "🔙", mn: "hew-po-STREH-fo ≈ \"HUE-po-STROPHE-o.\" A strophe is a turn — turn back: RETURN." },
      { g: "ὑστερέω", gloss: "I fall short of, lack", freq: 16, tier: "memorize", icon: "📉", mn: "hew-steh-REH-o ≈ \"HYSTER-eh-o.\" Hysteros is later — he came in last: I FALL SHORT." },
      { g: "φανερόω", gloss: "I reveal, make manifest, show", freq: 49, tier: "memorize", icon: "🔦", mn: "fah-neh-RO-o ≈ \"FAN-a-ROW-o.\" The fan blows the cover off the row: I REVEAL." },
      { g: "Φίλιππος, ὁ", gloss: "Philip", freq: 36, tier: "memorize", icon: "🧑", mn: "FEE-leep-pos ≈ \"PHILIP with an F.\" Philip." },
      { g: "χωρίς", gloss: "without, apart from", freq: 41, tier: "memorize", icon: "➗", mn: "kho-REES ≈ \"CHORES.\" He did the chores WITHOUT any help: apart from." },
      // ---- Vocabulary to Recognize (no built-in hook: these are pass-through) ----
      { g: "ἁμάρτημα, -ατος, τό", gloss: "sin, transgression", freq: 4, tier: "recognize" },
      { g: "ἀνοχή, ἡ", gloss: "forbearance, tolerance", freq: 2, tier: "recognize" },
      { g: "ἀπολύτρωσις, -εως, ἡ", gloss: "redemption, release, deliverance", freq: 10, tier: "recognize" },
      { g: "διαστολή, ἡ", gloss: "distinction, difference", freq: 3, tier: "recognize" },
      { g: "δωρεάν", gloss: "freely, as a gift, without payment", freq: 9, tier: "recognize" },
      { g: "εἴπερ", gloss: "if indeed, if perhaps", freq: 6, tier: "recognize" },
      { g: "ἐκκλείω", gloss: "I exclude, shut out", freq: 2, tier: "recognize" },
      { g: "ἔνδειξις, ἡ", gloss: "demonstration, proof", freq: 4, tier: "recognize" },
      { g: "ἱλαστήριον, τό", gloss: "propitiation", freq: 2, tier: "recognize" },
      { g: "καύχησις, ἡ", gloss: "boasting", freq: 11, tier: "recognize" },
      { g: "πάρεσις, ἡ", gloss: "passing over", freq: 1, tier: "recognize" },
      { g: "προγίνομαι", gloss: "it happens before, be done before", freq: 1, tier: "recognize" },
      { g: "προτίθημι", gloss: "I present, put forward, display publicly", freq: 3, tier: "recognize" },
      { g: "ὑπόδικος", gloss: "answerable, accountable", freq: 1, tier: "recognize" },
      { g: "φράσσω", gloss: "I shut, close", freq: 3, tier: "recognize" }
    ]
  },
  {
    id: "gd-set-03",
    source: "Going Deeper with New Testament Greek",
    chapter: 4,
    title: "Chapter 4 — Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀγοράζω", gloss: "I buy, purchase", freq: 30, tier: "memorize", icon: "🛒", mn: "ah-gho-RAH-zo ≈ \"the AGORA-zo.\" The ἀγορά is the marketplace — where you go to BUY." },
      { g: "ἀδικέω", gloss: "I do wrong, treat unjustly", freq: 28, tier: "memorize", icon: "⚖️", mn: "ah-thee-KEH-o ≈ \"a-THEE-KAY-o.\" ἀ- not + δίκη justice, with Koine δ as \"th\": I DO WRONG." },
      { g: "ἀληθινός", gloss: "true, real, genuine", freq: 28, tier: "memorize", icon: "💎", mn: "ah-lay-thee-NOS ≈ \"a-LAY-THEE-NOSE.\" Lay thee nose against it — no crack, no fake: GENUINE." },
      { g: "ἀνάγκη, ἡ", gloss: "necessity, pressure", freq: 17, tier: "memorize", icon: "⛓️", mn: "ah-NAHNG-kay ≈ \"a-NAG — KAY!\" A nag, Kay, that will not let up: NECESSITY, pressure." },
      { g: "ἅπαξ", gloss: "once and for all", freq: 14, tier: "memorize", icon: "1️⃣", mn: "HAH-pahx ≈ \"HA! — PACKS.\" He packs it away once, and never again: ONCE FOR ALL." },
      { g: "ἀρνίον, τό", gloss: "lamb, sheep", freq: 30, tier: "memorize", icon: "🐑", mn: "ahr-NEE-on ≈ \"ARE-KNEE-on.\" Down on your knees before the LAMB." },
      { g: "ἁρπάζω", gloss: "I grasp, snatch, seize", freq: 14, tier: "memorize", icon: "🫳", mn: "hahr-PAH-zo ≈ \"HARP-AH-zo.\" A harpy, and our HARPOON: it SNATCHES its prey." },
      { g: "Βαρναβᾶς, ὁ", gloss: "Barnabas", freq: 28, tier: "memorize", icon: "🤝", mn: "vahr-nah-VAHS ≈ \"VAR-na-VAHS.\" Both β's say \"v\" in Koine: BARNABAS." },
      { g: "γαμέω", gloss: "I marry", freq: 28, tier: "memorize", icon: "💍", mn: "ghah-MEH-o ≈ \"GAM-MAY-o.\" Our monoGAMY and biGAMY: I MARRY." },
      { g: "γνῶσις, -εως, ἡ", gloss: "knowledge", freq: 29, tier: "memorize", icon: "🧠", mn: "GHNO-sees ≈ \"g-NO-SEES.\" An aGNOStic is one without it: KNOWLEDGE." },
      { g: "διακρίνω", gloss: "I discriminate, judge, doubt", freq: 19, tier: "memorize", icon: "🤔", mn: "thee-ah-KREE-no ≈ \"THEE-a-CREE-no.\" διά through + κρίνω, our CRITIC: I JUDGE between — or waver and DOUBT." },
      { g: "ἐλεέω", gloss: "I have mercy on", freq: 29, tier: "memorize", icon: "🙏", mn: "eh-leh-EH-o ≈ \"EL-eh-EH-o.\" Kyrie ELEISON — Lord, HAVE MERCY." },
      { g: "ἔλεος, -ους, τό", gloss: "mercy, compassion", freq: 27, tier: "memorize", icon: "💗", mn: "EH-leh-os ≈ \"ELL-eh-oss.\" The noun standing behind eleison: MERCY itself." },
      { g: "ἐπιθυμία, ἡ", gloss: "lust, craving, desire", freq: 39, tier: "memorize", icon: "🔥", mn: "eh-pee-thew-MEE-ah ≈ \"a-PEA-THEW-ME-ah.\" ἐπί upon + θυμός passion — the heart set on it: CRAVING." },
      { g: "ἐπικαλέω", gloss: "I call (upon), name", freq: 30, tier: "memorize", icon: "📣", mn: "eh-pee-kah-LEH-o ≈ \"a-PEEK-a-LAY-o.\" ἐπί + καλέω, our CALL: I CALL UPON, I NAME." },
      { g: "ἐπιτιμάω", gloss: "I rebuke, reprove, warn", freq: 29, tier: "memorize", icon: "☝️", mn: "eh-pee-tee-MAH-o ≈ \"a-PEE-TEE-MA-o.\" τιμή is the price; ἐπι- sets one on your conduct: I REBUKE." },
      { g: "ἡγέομαι", gloss: "I lead, think, consider", freq: 28, tier: "memorize", icon: "🧭", mn: "hay-gheh-O-meh ≈ \"HAY-GAY-O-may.\" Our HEGEMONY: the one who LEADS — and so who RECKONS it best." },
      { g: "θυγάτηρ, -τρός, ἡ", gloss: "daughter, girl", freq: 28, tier: "memorize", icon: "👧", mn: "thew-GHAH-tayr ≈ \"THEW-GA-tare.\" One sound-shift from our own word: DAUGHTER." },
      { g: "θυσία, ἡ", gloss: "sacrifice, offering", freq: 28, tier: "memorize", icon: "🔥", mn: "thew-SEE-ah ≈ \"THEW-SEE-ah.\" You see the smoke go up: the SACRIFICE." },
      { g: "Ἰάκωβος, ὁ", gloss: "James", freq: 42, tier: "memorize", icon: "🧔", mn: "ee-ah-KO-vos ≈ \"ee-a-CO-VOS.\" Jacob in Greek dress — which English turned into JAMES." },
      { g: "ἴδε", gloss: "look, see, behold", freq: 29, tier: "memorize", icon: "👀", mn: "EE-theh ≈ \"EE-THE.\" One syllable and a pointing finger: LOOK!" },
      { g: "Ἰούδας, ὁ", gloss: "Jude, Judah, Judas", freq: 44, tier: "memorize", icon: "🪙", mn: "ee-OO-thahs ≈ \"ee-OO-THAHS.\" One name for all three: JUDAS, Jude, Judah." },
      { g: "Καῖσαρ, -αρος, ὁ", gloss: "Caesar, emperor", freq: 29, tier: "memorize", icon: "👑", mn: "KEH-sahr ≈ \"KAY-SAR.\" Not \"see-zer\" — Koine αι is \"eh\": CAESAR." },
      { g: "μάχαιρα, ἡ", gloss: "sword", freq: 29, tier: "memorize", icon: "🗡️", mn: "mah-KHEH-rah ≈ \"ma-KHAIR-ah\" (rasped: kh). A machete raised in her hand: the SWORD." },
      { g: "μιμνῄσκομαι", gloss: "I remember, recollect", freq: 23, tier: "memorize", icon: "🧵", mn: "meem-NAY-sko-meh ≈ \"MEME-NAY-sko-may.\" Same root as aMNESia — but here you REMEMBER." },
      { g: "μισέω", gloss: "I hate, detest", freq: 40, tier: "memorize", icon: "😠", mn: "mee-SEH-o ≈ \"ME-SAY-o.\" A MISanthrope says it of everyone: I HATE." },
      { g: "μισθός, ὁ", gloss: "pay, wages, reward", freq: 29, tier: "memorize", icon: "💵", mn: "mees-THOS ≈ \"MEECE-THOSS.\" What is counted out at the end of the day: WAGES." },
      { g: "παράκλησις, -εως, ἡ", gloss: "encouragement, comfort", freq: 29, tier: "memorize", icon: "🫂", mn: "pah-rah-KLAY-sees ≈ \"PARA-CLAY-sees.\" The PARACLETE is called alongside you: COMFORT." },
      { g: "παρέρχομαι", gloss: "I pass by, neglect, disobey", freq: 29, tier: "memorize", icon: "🚶", mn: "pah-REHR-kho-meh ≈ \"pa-RARE-ko-may\" (rasped: kh). παρά alongside + ἔρχομαι come: I PASS BY." },
      { g: "πάσχα, τό", gloss: "Passover", freq: 29, tier: "memorize", icon: "🍷", mn: "PAHS-khah ≈ \"PAS-KHA.\" Pascha itself, barely changed: the PASSOVER." },
      { g: "ποτέ", gloss: "once, formerly, ever", freq: 29, tier: "memorize", icon: "🕰️", mn: "po-TEH ≈ \"po-TAY.\" \"Once upon a po-TAY\" — ONCE, formerly, ever." },
      { g: "σκανδαλίζω", gloss: "I cause to stumble", freq: 29, tier: "memorize", icon: "🪨", mn: "skahn-thah-LEE-zo ≈ \"SCAN-THAL-ee-zo.\" Spelled σκανδαλ-, our SCANDAL — Koine δ says \"th\": I MAKE THEM STUMBLE." },
      { g: "σκότος, -ους, τό", gloss: "darkness", freq: 31, tier: "memorize", icon: "🌑", mn: "SKO-tos ≈ \"SCO-TOSS.\" Toss the lamp out and this is what is left: DARKNESS." },
      { g: "συνείδησις, -εως, ἡ", gloss: "conscience", freq: 30, tier: "memorize", icon: "💭", mn: "sew-nee-THAY-sees ≈ \"SEW-knee-THEY-sees.\" σύν with + οἶδα know — knowing along with yourself: CONSCIENCE." },
      { g: "σωτήρ, -ῆρος, ὁ", gloss: "savior, deliverer", freq: 24, tier: "memorize", icon: "🛟", mn: "so-TAYR ≈ \"so-TARE.\" SOTERiology is the doctrine of him: the SAVIOR." },
      { g: "σωτηρία, ἡ", gloss: "salvation, deliverance", freq: 46, tier: "memorize", icon: "✝️", mn: "so-tay-REE-ah ≈ \"so-tay-REE-ah.\" What the σωτήρ brings with him: SALVATION." },
      { g: "φίλος", gloss: "beloved, friend", freq: 29, tier: "memorize", icon: "🫶", mn: "FEE-los ≈ \"FEEL-oss.\" PHILadelphia is love of the brother: a FRIEND, beloved." },
      { g: "φόβος, ὁ", gloss: "fear, reverence, respect", freq: 47, tier: "memorize", icon: "😨", mn: "FO-vos ≈ \"FOE-VOSS.\" Our PHOBIA — but here it can also mean reverence: FEAR." },
      { g: "φυλάσσω", gloss: "I guard, protect", freq: 31, tier: "memorize", icon: "🛡️", mn: "few-LAHS-so ≈ \"a-FEW-LASSO.\" A few lassos thrown round the flock: I GUARD." },
      { g: "φυλή, ἡ", gloss: "tribe, nation, people", freq: 31, tier: "memorize", icon: "🏕️", mn: "few-LAY ≈ \"a-FEW-LAY.\" A few lay claim to one bloodline: a TRIBE." },
      // ---- Vocabulary to Recognize ----
      // Read once and move on, so these carry no built-in hook.
      { g: "ἀγαλλίασις, ἡ", gloss: "exultation", freq: 5, tier: "recognize" },
      { g: "ἄμωμος", gloss: "blameless", freq: 8, tier: "recognize" },
      { g: "ἀποδιορίζω", gloss: "I divide, separate", freq: 1, tier: "recognize" },
      { g: "ἄπταιστος", gloss: "without stumbling", freq: 1, tier: "recognize" },
      { g: "ἀσέβεια, ἡ", gloss: "impiety", freq: 6, tier: "recognize" },
      { g: "ἐλεάω", gloss: "I have mercy on", freq: 3, tier: "recognize" },
      { g: "ἐμπαίκτης, -ου, ὁ", gloss: "mocker", freq: 2, tier: "recognize" },
      { g: "ἐπαγωνίζομαι", gloss: "I contend", freq: 1, tier: "recognize" },
      { g: "ἐποικοδομέω", gloss: "I edify, build up/on", freq: 7, tier: "recognize" },
      { g: "κατενώπιον", gloss: "opposite, in the presence of", freq: 3, tier: "recognize" },
      { g: "κλητός", gloss: "called, invited", freq: 10, tier: "recognize" },
      { g: "κοινός", gloss: "communal, common", freq: 14, tier: "recognize" },
      { g: "κράτος, τό", gloss: "power, rule", freq: 12, tier: "recognize" },
      { g: "μεγαλωσύνη, ἡ", gloss: "majesty", freq: 3, tier: "recognize" },
      { g: "πληθύνω", gloss: "I multiply, grow, increase", freq: 12, tier: "recognize" },
      { g: "προλέγω", gloss: "I foretell, proclaim beforehand", freq: 12, tier: "recognize" },
      { g: "προσδέχομαι", gloss: "I wait for", freq: 14, tier: "recognize" },
      { g: "σπιλόω", gloss: "I stain, defile", freq: 2, tier: "recognize" },
      { g: "σπουδή, ἡ", gloss: "eagerness, earnestness, diligence", freq: 12, tier: "recognize" },
      { g: "χιτών, -ῶνος, ὁ", gloss: "garment, shirt", freq: 11, tier: "recognize" },
      { g: "ψυχικός", gloss: "natural, unspiritual, worldly", freq: 6, tier: "recognize" },
    ]
  },
  {
    id: "gd-set-04",
    source: "Going Deeper with New Testament Greek",
    chapter: 5,
    title: "Chapter 5 — Vocabulary",
    words: [
      // ---- Vocabulary to Memorize ----
      { g: "ἀδικία, ἡ", gloss: "unrighteousness, injustice", freq: 25, tier: "memorize", icon: "⚖️", mn: "ah-thee-KEE-ah ≈ \"a-THEE-KEY-ah.\" ἀ- not + δίκη justice, Koine δ as \"th\": INJUSTICE." },
      { g: "ἀληθής", gloss: "true, honest, genuine", freq: 26, tier: "memorize", icon: "✔️", mn: "ah-lay-THAYS ≈ \"a-LAY-THAYS.\" Lay it out and nothing is hidden: TRUE, honest." },
      { g: "ἀναβλέπω", gloss: "I look up, see again, receive sight", freq: 25, tier: "memorize", icon: "👁️", mn: "ah-nah-VLEH-po ≈ \"ANNA-VLEP-o.\" ἀνά up + βλέπω see: I LOOK UP — and the blind SEE AGAIN." },
      { g: "ἄρτι", gloss: "now", freq: 36, tier: "memorize", icon: "⏱️", mn: "AHR-tee ≈ \"ARTY.\" The arty crowd care about nothing but NOW." },
      { g: "ἀσθενής", gloss: "weak, powerless, sick", freq: 26, tier: "memorize", icon: "🤒", mn: "ahs-theh-NAYS ≈ \"as-THEN-AYS.\" Our ASTHENIA, without strength: WEAK, sick." },
      { g: "βαστάζω", gloss: "I bear, endure", freq: 27, tier: "memorize", icon: "🎒", mn: "vahs-TAH-zo ≈ \"VAS-TAH-zo.\" Spelled βαστ- but Koine β says \"v\": he hoists the vase and BEARS it." },
      { g: "γάμος, ὁ", gloss: "wedding, marriage", freq: 16, tier: "memorize", icon: "💒", mn: "GHAH-mos ≈ \"GAM-oss.\" MonoGAMy is one of these: a MARRIAGE." },
      { g: "γέ", gloss: "indeed, even", freq: 25, tier: "memorize", icon: "❗", mn: "GHEH ≈ \"GEH\" (hard g). One breath of emphasis and no more: INDEED." },
      { g: "γεύομαι", gloss: "I taste, experience", freq: 15, tier: "memorize", icon: "👅", mn: "GHEV-o-meh ≈ \"GAV-o-may.\" Gav gave me a spoonful to TASTE." },
      { g: "γνωρίζω", gloss: "I make known, reveal, know", freq: 25, tier: "memorize", icon: "📣", mn: "ghno-REE-zo ≈ \"g-NO-REE-zo.\" Built on γνῶσις, knowledge: I MAKE IT KNOWN." },
      { g: "δέκα", gloss: "ten", freq: 25, tier: "memorize", icon: "🔟", mn: "THEH-kah ≈ \"THECK-ah.\" Our DECAthlon and DECAde — Koine δ says \"th\": TEN." },
      { g: "δένδρον, τό", gloss: "tree", freq: 25, tier: "memorize", icon: "🌳", mn: "THEHN-thron ≈ \"THEN-THRON.\" A rhoDODENDRon is a rose-TREE." },
      { g: "διάκονος, ὁ", gloss: "servant, deacon", freq: 29, tier: "memorize", icon: "🍽️", mn: "thee-AH-ko-nos ≈ \"THEE-A-ko-nos.\" Spelled δια-, our DEACON: a SERVANT." },
      { g: "δουλεύω", gloss: "I am a slave, serve, obey", freq: 25, tier: "memorize", icon: "⛓️", mn: "thoo-LEV-o ≈ \"THOO-LEV-o.\" A δοῦλος is a slave, and this is his life: I SERVE." },
      { g: "ἐκχέω", gloss: "I pour out, shed", freq: 27, tier: "memorize", icon: "🫗", mn: "ehk-KHEH-o ≈ \"eck-KAY-o\" (rasped: kh). ἐκ out + χέω pour: I POUR IT OUT." },
      { g: "Ἕλλην, -ηνος, ὁ", gloss: "a Greek, gentile, pagan", freq: 25, tier: "memorize", icon: "🏛️", mn: "HEHL-layn ≈ \"HELL-ayn.\" HELLENistic is named for him: a GREEK." },
      { g: "ἕνεκα", gloss: "because of, on account of, for the sake of", freq: 26, tier: "memorize", icon: "➡️", mn: "HEH-neh-kah ≈ \"HEN-eh-ka.\" All this fuss on account of one hen: BECAUSE OF." },
      { g: "ἥκω", gloss: "I have come", freq: 26, tier: "memorize", icon: "🚪", mn: "HAY-ko ≈ \"HAY-ko.\" Hay-ho — I HAVE COME." },
      { g: "Ἰακώβ, ὁ", gloss: "Jacob", freq: 27, tier: "memorize", icon: "🪜", mn: "ee-ah-KOV ≈ \"ee-a-COV.\" The Hebrew form left undressed: JACOB." },
      { g: "καθαρός", gloss: "clean, pure", freq: 27, tier: "memorize", icon: "🫧", mn: "kah-thah-ROS ≈ \"ka-THA-ROSE.\" A CATHARtic leaves you CLEAN, pure." },
      { g: "κεῖμαι", gloss: "I lie, recline", freq: 24, tier: "memorize", icon: "🛏️", mn: "KEE-meh ≈ \"KEY-may.\" The key may just LIE there where it fell." },
      { g: "λυπέω", gloss: "I grieve, offend", freq: 26, tier: "memorize", icon: "😢", mn: "lew-PEH-o ≈ \"LOO-PAY-o.\" Loo, pay up — and it GRIEVES you." },
      { g: "Μαρία, ἡ", gloss: "Mary", freq: 27, tier: "memorize", icon: "👩", mn: "mah-REE-ah ≈ \"ma-REE-ah.\" The Greek spelling: MARY." },
      { g: "Μαριάμ, ἡ", gloss: "Mary", freq: 27, tier: "memorize", icon: "👩", mn: "mah-ree-AHM ≈ \"ma-ree-AHM.\" The Hebrew spelling of the same name: MARY." },
      { g: "μυστήριον, τό", gloss: "mystery, secret", freq: 28, tier: "memorize", icon: "🔐", mn: "mews-TAY-ree-on ≈ \"MUSE-TAY-ree-on.\" Straight across into English: MYSTERY." },
      { g: "νικάω", gloss: "I conquer, overcome", freq: 28, tier: "memorize", icon: "🏆", mn: "nee-KAH-o ≈ \"NIKE-ah-o.\" NIKE is victory herself: I CONQUER." },
      { g: "νυμφίος, ὁ", gloss: "bridegroom", freq: 16, tier: "memorize", icon: "🤵", mn: "newm-FEE-os ≈ \"NUMF-EE-os.\" The NYMPH is the bride; this is her man: the BRIDEGROOM." },
      { g: "οἶνος, ὁ", gloss: "wine", freq: 34, tier: "memorize", icon: "🍷", mn: "EW-nos ≈ \"EW-nos.\" Koine οι says \"ew\"; our OENOlogy is the study of WINE." },
      { g: "πνευματικός", gloss: "spiritual", freq: 26, tier: "memorize", icon: "🕊️", mn: "pnev-mah-tee-KOS ≈ \"p-NEV-ma-TEE-kos.\" πνεῦμα is breath and spirit — PNEUMAtic: SPIRITUAL." },
      { g: "πόθεν", gloss: "from where?", freq: 29, tier: "memorize", icon: "🧭", mn: "PO-thehn ≈ \"PO-THEN.\" Po — then where did it come from? FROM WHERE?" },
      { g: "πόσος", gloss: "how great/much/many (?)", freq: 27, tier: "memorize", icon: "📏", mn: "PO-sos ≈ \"PO-SOS.\" An SOS always asks HOW MUCH is left." },
      { g: "προφητεύω", gloss: "I prophesy", freq: 28, tier: "memorize", icon: "📜", mn: "pro-fay-TEV-o ≈ \"pro-fay-TEV-o.\" Say it aloud and it is already the word: I PROPHESY." },
      { g: "σός", gloss: "your", freq: 27, tier: "memorize", icon: "🫵", mn: "SOS ≈ \"SOSS.\" Short, blunt and possessive: YOUR." },
      { g: "σταυρός, ὁ", gloss: "cross", freq: 27, tier: "memorize", icon: "✝️", mn: "stav-ROS ≈ \"STAV-ROSE.\" The noun behind σταυρόω, and a stave of wood: the CROSS." },
      { g: "στρατιώτης, -ου, ὁ", gloss: "soldier", freq: 26, tier: "memorize", icon: "🪖", mn: "strah-tee-O-tays ≈ \"STRAT-ee-O-tays.\" STRATegy is his trade: a SOLDIER." },
      { g: "συνίημι", gloss: "I understand, comprehend", freq: 26, tier: "memorize", icon: "💡", mn: "sew-NEE-ay-mee ≈ \"SEW-KNEE-ay-me.\" σύν together + ἵημι send: you put it together and UNDERSTAND." },
      { g: "τελέω", gloss: "I finish, complete", freq: 28, tier: "memorize", icon: "🏁", mn: "teh-LEH-o ≈ \"TELL-AY-o.\" τέλος is the end — tell them it is FINISHED." },
      { g: "φρονέω", gloss: "I think, ponder", freq: 26, tier: "memorize", icon: "🤔", mn: "fro-NEH-o ≈ \"FRO-NAY-o.\" SchizoPHRENia splits this very thing: the mind — I THINK." },
      { g: "φωνέω", gloss: "I call", freq: 43, tier: "memorize", icon: "📞", mn: "fo-NEH-o ≈ \"FONE-AY-o.\" A phone exists for exactly this: I CALL." },
      { g: "χήρα, ἡ", gloss: "widow", freq: 26, tier: "memorize", icon: "🕯️", mn: "KHAY-rah ≈ \"KAY-rah\" (rasped: kh). Kay, left on her own now: the WIDOW." },
      // ---- Vocabulary to Recognize ----
      // Read once and move on, so these carry no built-in hook.
      { g: "ἀνά", gloss: "each", freq: 13, tier: "recognize" },
      { g: "ἀντλέω", gloss: "I draw (water)", freq: 4, tier: "recognize" },
      { g: "ἄνω", gloss: "above", freq: 9, tier: "recognize" },
      { g: "ἀρχιτρίκλινος, ὁ", gloss: "headwaiter", freq: 3, tier: "recognize" },
      { g: "γεμίζω", gloss: "I fill", freq: 8, tier: "recognize" },
      { g: "ἐλάσσων", gloss: "inferior, of lesser quality", freq: 4, tier: "recognize" },
      { g: "ἕξ", gloss: "six", freq: 13, tier: "recognize" },
      { g: "καθαρισμός, ὁ", gloss: "purification", freq: 7, tier: "recognize" },
      { g: "Κανά, ἡ", gloss: "Cana", freq: 4, tier: "recognize" },
      { g: "λίθινος", gloss: "(made of) stone", freq: 3, tier: "recognize" },
      { g: "μεθύσκω", gloss: "I get drunk", freq: 5, tier: "recognize" },
      { g: "μετρητής, -οῦ, ὁ", gloss: "measure", freq: 1, tier: "recognize" },
      { g: "ὑδρία, ἡ", gloss: "water jar", freq: 3, tier: "recognize" },
      { g: "χωρέω", gloss: "I contain", freq: 10, tier: "recognize" },
    ]
  }
];
