// Sync for the vocabulary app: the phone pushes up which mnemonics are marked
// Keep or Replace, and pulls down rewritten ones. That is what lets a rewrite
// be done for you and simply arrive, instead of being copied back and forth.
//
// No secrets to configure: Supabase gives its own functions SUPABASE_URL and
// SUPABASE_SERVICE_ROLE_KEY. The tables have RLS on with no policies, so they
// are reachable only through here.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "content-type",
  "Access-Control-Max-Age": "86400",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "content-type": "application/json" },
  });

// A device id is generated by the app and never leaves it except to name these
// rows, so it doubles as the only thing guarding them.
const ID_OK = /^[A-Za-z0-9_-]{16,64}$/;
const MAX_HOOKS_BYTES = 512 * 1024;

const db = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return json({ error: "POST only." }, 405);

  let body: { action?: string; device?: string; label?: string; hooks?: unknown };
  try { body = await req.json(); } catch { return json({ error: "Body must be JSON." }, 400); }

  const device = String(body.device ?? "");
  if (!ID_OK.test(device)) return json({ error: "Bad device id." }, 400);

  if (body.action === "push") {
    const hooks = body.hooks ?? {};
    if (typeof hooks !== "object" || Array.isArray(hooks)) {
      return json({ error: "hooks must be an object." }, 400);
    }
    if (JSON.stringify(hooks).length > MAX_HOOKS_BYTES) {
      return json({ error: "Too much to sync." }, 413);
    }
    const { error } = await db.from("vocab_devices").upsert({
      device_id: device,
      label: typeof body.label === "string" ? body.label.slice(0, 120) : null,
      hooks,
      updated_at: new Date().toISOString(),
    });
    if (error) return json({ error: error.message }, 500);
    return json({ ok: true });
  }

  if (body.action === "pull") {
    // Registering here too, so a first pull from a fresh phone still creates
    // the row a replacement has to point at.
    await db.from("vocab_devices")
      .upsert({ device_id: device }, { onConflict: "device_id", ignoreDuplicates: true });

    const { data, error } = await db
      .from("vocab_replacements")
      .select("id, word_id, mn")
      .eq("device_id", device)
      .is("delivered_at", null)
      .order("id");
    if (error) return json({ error: error.message }, 500);

    const rows = data ?? [];
    if (rows.length) {
      await db.from("vocab_replacements")
        .update({ delivered_at: new Date().toISOString() })
        .in("id", rows.map((r) => r.id));
    }
    return json({ replacements: rows.map((r) => ({ id: r.word_id, mn: r.mn })) });
  }

  return json({ error: "action must be push or pull." }, 400);
});
